### ISSUE TITLE
ffmpeg编译相关工程能上传么

### ISSUE THREAD

**Issue by Android4MediaPlayer** [xufuji456/FFmpegAndroid#1]
开源维护起来就全套了

**Comment by xufuji456** [comment]
你好，感谢你的建议，ffmpeg源码在这里可以下载：http://ffmpeg.org/download.html
由于源码不断更新，这里上传上去也需要不断更新，鉴于此考虑没有上传。

**Comment by wnpllrzodiac** [comment]
其实ffmpeg源码不需要，只提供编译编译脚本就可以了。网上好多啊，不过不明就里的人用起来，最好还是服务做全套哈。

**Comment by xufuji456** [comment]
嗯，这个提议不错，后续会上传
