### ISSUE TITLE
绿屏和内存问题

### ISSUE THREAD

**Issue by hnyer** [xufuji456/FFmpegAndroid#10]
华为平板 M2  ， 服务器是用你推荐的https://download.csdn.net/download/u011686167/10538305  。

1、在开启声音的时候 ，报错 
将静音打开时 会报错  “音频编码失败...   Fatal signal 11 (SIGSEGV), code 1, fault addr 0xc72e9fd4 in tid 7031 (Thread-5)”     

2、关闭静音的时候 ，是绿屏 
![img_0298](https://user-images.githubusercontent.com/5989755/42751134-502519be-891c-11e8-9a4f-87a6fef9395c.JPG)

**Comment by xufuji456** [comment]
绿屏问题应该是分辨率不对，你在LiveActivity中使用下面这些分辨率修改（width和Height）试下：
华为平板M2支持的预览分辨率大小：
1280x720
1280x960
1440x1080
1920x1080
208x144
176x144
352x288
320x240
960x544
960x720
720x720

**Comment by hnyer** [comment]
@xufuji456    
![snipaste_20180717_093609](https://user-images.githubusercontent.com/5989755/42791772-de380044-89a4-11e8-8cde-75960b6d1715.png)

1、 试了1280x720 不报错 （但是任然绿屏），其他的都会报这个错 。   
Process: com.frank.ffmpeg, PID: 21417   java.lang.RuntimeException: setParameters failed 。

2、另外延时性好像比较厉害 ，（局域网）有四五秒的样子，这样的效果应该没法用于实际应用。 指点一下从哪个方面可以进行优化 。

**Comment by xufuji456** [comment]
RTMP是有一定延时，因为音视频流先推到RTMP服务器，客户端然后再从服务器拉流播放。
如果要求实时性比较好，建议使用rtsp，局域网1080p视频可以做到延时130ms左右
（当然播放器得无解码延时、无缓冲队列）。
