### ISSUE TITLE
这个标志符都找不到，请问这是什么原因

### ISSUE THREAD

**Issue by zorro0799** [xufuji456/FFmpegAndroid#100]
编译环境
android studio  3.5.3 ide导入
classpath 'com.android.tools.build:gradle:3.5.3'
ndk 版本 20.1.5948944

[15/15] Linking CXX shared library ../../../../build/intermediates/cmake/debug/obj/armeabi-v7a/libmedia-handle.so
  FAILED: : && /Users/EddyHu/Works/Developer/Tools/Android/sdk/ndk-bundle/toolchains/llvm/prebuilt/darwin-x86_64/bin/clang++  --target=armv7-none-linux-androideabi21 --gcc-toolchain=/Users/EddyHu/Works/Developer/Tools/Android/sdk/ndk-bundle/toolchains/llvm/prebuilt/darwin-x86_64 --sysroot=/Users/EddyHu/Works/Developer/Tools/Android/sdk/ndk-bundle/toolchains/llvm/prebuilt/darwin-x86_64/sysroot -fPIC -g -DANDROID -fdata-sections -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -fno-addrsig -march=armv7-a -mthumb -Wa,--noexecstack -Wformat -Werror=format-security   -std=gnu++11 -O0 -fno-limit-debug-info  -Wl,--exclude-libs,libgcc.a -Wl,--exclude-libs,libatomic.a -static-libstdc++ -Wl,--build-id -Wl,--warn-shared-textrel -Wl,--fatal-warnings -Wl,--exclude-libs,libunwind.a -Wl,--no-undefined -Qunused-arguments -Wl,-z,noexecstack -shared -Wl,-soname,libmedia-handle.so -o ../../../../build/intermediates/cmake/debug/obj/armeabi-v7a/libmedia-handle.so CMakeFiles/media-handle.dir/src/main/cpp/ffmpeg/cmdutils.c.o CMakeFiles/media-handle.dir/src/main/cpp/ffmpeg/ffmpeg.c.o CMakeFiles/media-handle.dir/src/main/cpp/ffmpeg/ffmpeg_filter.c.o CMakeFiles/media-handle.dir/src/main/cpp/ffmpeg/ffmpeg_opt.c.o CMakeFiles/media-handle.dir/src/main/cpp/ffmpeg_cmd.c.o CMakeFiles/media-handle.dir/src/main/cpp/audio_player.c.o CMakeFiles/media-handle.dir/src/main/cpp/openSL_audio_player.c.o CMakeFiles/media-handle.dir/src/main/cpp/video_player.c.o CMakeFiles/media-handle.dir/src/main/cpp/ffmpeg_pusher.cpp.o CMakeFiles/media-handle.dir/src/main/cpp/AVpacket_queue.c.o CMakeFiles/media-handle.dir/src/main/cpp/media_player.c.o CMakeFiles/media-handle.dir/src/main/cpp/video_filter.c.o CMakeFiles/media-handle.dir/src/main/cpp/audio_lame.c.o CMakeFiles/media-handle.dir/src/main/cpp/fast_start.c.o  ../../../../libs/armeabi-v7a/libffmpeg.so -landroid -ljnigraphics -lOpenSLES -llog -latomic -lm && :
  /Users/EddyHu/Works/Developer/Workspace/Android/FFmpegAndroid-master/app/src/main/cpp/audio_lame.c:9: error: undefined reference to 'lame_init'
  /Users/EddyHu/Works/Developer/Workspace/Android/FFmpegAndroid-master/app/src/main/cpp/audio_lame.c:10: error: undefined reference to 'lame_init_params'
  /Users/EddyHu/Works/Developer/Workspace/Android/FFmpegAndroid-master/app/src/main/cpp/audio_lame.c:22: error: undefined reference to 'lame_init'
  /Users/EddyHu/Works/Developer/Workspace/Android/FFmpegAndroid-master/app/src/main/cpp/audio_lame.c:23: error: undefined reference to 'lame_set_in_samplerate'
  /Users/EddyHu/Works/Developer/Workspace/Android/FFmpegAndroid-master/app/src/main/cpp/audio_lame.c:24: error: undefined reference to 'lame_set_num_channels'
  /Users/EddyHu/Works/Developer/Workspace/Android/FFmpegAndroid-master/app/src/main/cpp/audio_lame.c:25: error: undefined reference to 'lame_set_out_samplerate'
  /Users/EddyHu/Works/Developer/Workspace/Android/FFmpegAndroid-master/app/src/main/cpp/audio_lame.c:26: error: undefined reference to 'lame_set_brate'
  /Users/EddyHu/Works/Developer/Workspace/Android/FFmpegAndroid-master/app/src/main/cpp/audio_lame.c:27: error: undefined reference to 'lame_set_quality'
  /Users/EddyHu/Works/Developer/Workspace/Android/FFmpegAndroid-master/app/src/main/cpp/audio_lame.c:28: error: undefined reference to 'lame_set_scale'
  /Users/EddyHu/Works/Developer/Workspace/Android/FFmpegAndroid-master/app/src/main/cpp/audio_lame.c:29: error: undefined reference to 'lame_set_VBR_q'
  /Users/EddyHu/Works/Developer/Workspace/Android/FFmpegAndroid-master/app/src/main/cpp/audio_lame.c:30: error: undefined reference to 'lame_set_VBR_mean_bitrate_kbps'
  /Users/EddyHu/Works/Developer/Workspace/Android/FFmpegAndroid-master/app/src/main/cpp/audio_lame.c:31: error: undefined reference to 'lame_set_lowpassfreq'
  /Users/EddyHu/Works/Developer/Workspace/Android/FFmpegAndroid-master/app/src/main/cpp/audio_lame.c:32: error: undefined reference to 'lame_set_highpassfreq'
  /Users/EddyHu/Works/Developer/Workspace/Android/FFmpegAndroid-master/app/src/main/cpp/audio_lame.c:36: error: undefined reference to 'lame_set_mode'
  /Users/EddyHu/Works/Developer/Workspace/Android/FFmpegAndroid-master/app/src/main/cpp/audio_lame.c:39: error: undefined reference to 'lame_set_mode'
  /Users/EddyHu/Works/Developer/Workspace/Android/FFmpegAndroid-master/app/src/main/cpp/audio_lame.c:42: error: undefined reference to 'lame_set_mode'
  /Users/EddyHu/Works/Developer/Workspace/Android/FFmpegAndroid-master/app/src/main/cpp/audio_lame.c:45: error: undefined reference to 'lame_set_mode'
  /Users/EddyHu/Works/Developer/Workspace/Android/FFmpegAndroid-master/app/src/main/cpp/audio_lame.c:54: error: undefined reference to 'lame_set_VBR'
  /Users/EddyHu/Works/Developer/Workspace/Android/FFmpegAndroid-master/app/src/main/cpp/audio_lame.c:57: error: undefined reference to 'lame_set_VBR'
  /Users/EddyHu/Works/Developer/Workspace/Android/FFmpegAndroid-master/app/src/main/cpp/audio_lame.c:60: error: undefined reference to 'lame_set_VBR'
  /Users/EddyHu/Works/Developer/Workspace/Android/FFmpegAndroid-master/app/src/main/cpp/audio_lame.c:63: error: undefined reference to 'lame_set_VBR'
  /Users/EddyHu/Works/Developer/Workspace/Android/FFmpegAndroid-master/app/src/main/cpp/audio_lame.c:97: error: undefined reference to 'id3tag_init'
  /Users/EddyHu/Works/Developer/Workspace/Android/FFmpegAndroid-master/app/src/main/cpp/audio_lame.c:100: error: undefined reference to 'id3tag_set_title'
  /Users/EddyHu/Works/Developer/Workspace/Android/FFmpegAndroid-master/app/src/main/cpp/audio_lame.c:104: error: undefined reference to 'id3tag_set_artist'

**Comment by xufuji456** [comment]
这是mp3lame库找不到的报错。
我不久前更新过代码，你更新代码试下。
