### ISSUE TITLE
h264转码崩溃，大佬我这有日志和当时的so文件

### ISSUE THREAD

**Issue by feigestar** [xufuji456/FFmpegAndroid#103]
转码命令:
ffmpeg -i ../VID_20200106_17572882.mp4 -b:v 1300k -s 540x960 -vcodec libx264 -preset ultrafast -crf 24 ../com.jakarta.baca/7bc2.mp4

您邮箱是多少我把日志和崩溃的so文件发给您

**Comment by xufuji456** [comment]
-crf 24是什么命令呢，你是想设置帧率还是什么？
我邮箱839789740@qq.com
