### ISSUE TITLE
请问H264裸流解码播放该怎么集成呢？

### ISSUE THREAD

**Issue by CrazyDoraemon** [xufuji456/FFmpegAndroid#104]
作者你好，我现在需要通过TCP获取H264的裸流进行播放，该如何使用这个库进行一帧一帧的解码呢？

**Comment by xufuji456** [comment]
你可以参考下app/src/main/cpp/video_player.c这个类，传文件路径和surface进来，边解码边渲染。

**Comment by CrazyDoraemon** [comment]
> 你可以参考下app/src/main/cpp/video_player.c这个类，传文件路径和surface进来，边解码边渲染。

有直接解码的方法吗，传入一帧h264，返回一帧解码数据，C语言方法不会用啊

**Comment by xufuji456** [comment]
目前没有，可以基于video_player.c修改一下
