### ISSUE TITLE
支持h265和aac的混流封装成mp4吗

### ISSUE THREAD

**Issue by pie-tk** [xufuji456/FFmpegAndroid#105]

**Comment by xufuji456** [comment]
目前没有集成x265编码器，你的问题分两种情况：
1、如果是输入h265和aac文件流，是可以封装成mp4的；
2、如果视频流原本不是265编码，无法转码成h265，也就无法封装成mp4；

**Comment by pie-tk** [comment]
@xufuji456 恩 是编码好的h265 aac的byte[]流

**Comment by xufuji456** [comment]
你把两个流分别写到文件里，调用音视频里面的音视频合成试下

**Comment by xufuji456** [comment]
还有一种方式，使用Android系统的MediaMuxer也可以

**Comment by pie-tk** [comment]
@xufuji456 先保存再合成感觉有点奇怪，没其他方式的时候倒是可以试试，MediaMuxer试过，但合成后的mp4一直播不了

**Comment by xufuji456** [comment]
你如果不想保存文件，我想到两种方法：
1、使用http代理音视频字节流，传递给ffmpeg去进行合成；
2、修改ffmpeg源码，原来是读取文件流/网络流，改成直接输入字节数组去合成(难度相对大一点)；

**Comment by pie-tk** [comment]
看来这个需求不是很容易，刚刚编译了FFmpeg的库，准备研究一下，感谢你的回答！

**Comment by xufuji456** [comment]
http代理音视频字节流，我试过这种方案是可以的。要写一个http代理服务，你试一下。

**Comment by pie-tk** [comment]
恩，好的，后续试试，感谢！

**Comment by xufuji456** [comment]
不用客气
