### ISSUE TITLE
我尝试了合并h265和aac文件，会出现问题。

### ISSUE THREAD

**Issue by pie-tk** [xufuji456/FFmpegAndroid#109]
合成之后的mp4文件有两种情况：
1.自己定了个时间参数，合成之后有视频，没声音；
2.去掉时间，也就是忽略时间参数，所合成的mp4画面只有第一帧画面，不会动，有声音。

另外，合成h264-aac在给了时间参数的时候也是出现没有声音只有视频的情况，忽略时间后声画都有，但这样封装的mp4显示的时间是有问题的

**Comment by xufuji456** [comment]
是h265还是h264

**Comment by pie-tk** [comment]
@xufuji456 
合成之后的mp4文件有两种情况：（h265+aac）
1.自己定了个时间参数，合成之后有视频，没声音；
2.去掉时间，也就是忽略时间参数，所合成的mp4画面只有第一帧画面，不会动，有声音。

（h264+aac）
另外，合成h264-aac在给了时间参数的时候也是出现没有声音只有视频的情况，忽略时间后声画都有，但这样封装的mp4显示的时间是有问题的

**Comment by xufuji456** [comment]
h265编码器目前没有编译进去，暂时不支持
