### ISSUE TITLE
音视频合并并调整音量，直接退出

### ISSUE THREAD

**Issue by shuaisong** [xufuji456/FFmpegAndroid#113]
"ffmpeg -i %s -i %s -filter_complex [0:a]aformat=sample_fmts=fltp:sample_rates=44100:channel_layouts=stereo,volume=0.9[a0]; [1:a]aformat=sample_fmts=fltp:sample_rates=44100:channel_layouts=stereo,volume=0.5[a1]; [a0][a1]amix=inputs=2:duration=first[aout]\" -map \"[aout]\" -ac 2 -c:v copy -map 0:v:0 %s";

**Comment by AkarinLiu** [comment]
？？？
________________________________

**Comment by shuaisong** [comment]
没办法调整音量

**Comment by shuaisong** [comment]
Fatal signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x0 in tid 6021 (Thread-3), pid 5656

**Comment by xufuji456** [comment]
最后的表情符号是什么
