### ISSUE TITLE
进行采样率修改的时候，如果生成的是MP3文件，改mp3文件的时长会变成0

### ISSUE THREAD

**Issue by code1k** [xufuji456/FFmpegAndroid#114]
进行采样率修改的时候，如果生成的是MP3文件，改mp3文件的时长会变成0。请问是怎么回事？

**Comment by xufuji456** [comment]
你写的命令行是怎么样的

**Comment by code1k** [comment]
ffmpeg -i a.mp3 -ar 44100 b.mp3
其中a.mp3的采样率是48000。

**Comment by xufuji456** [comment]
我试了转换采样率后，时长是正常的，你换个mp3试下，确认mp3原文件有没问题

**Comment by xufuji456** [comment]
另外确认下，你使用ffmpeg.so有没带mp3lame

**Comment by code1k** [comment]
我是使用的是一个采样率48000的MP3文件，转换以后我是导出来使用格式工厂查看的，而且使用win10自带的播放器也是采集不到时长的。

**Comment by code1k** [comment]
都是使用你项目里面的so库的

**Comment by code1k** [comment]
应该是我格式工厂的问题以及以前so库的问题，现在正常了，谢谢！
