### ISSUE TITLE
去水印同样的参数怎么同pc版的 效果差很多呢

### ISSUE THREAD

**Issue by fecloud** [xufuji456/FFmpegAndroid#115]
你编译的是什么版本的

**Comment by fecloud** [comment]
libavutil      56. 18.102 / 56. 18.102
  libavcodec     58. 19.102 / 58. 19.102
  libavformat    58. 15.100 / 58. 15.100
  libavdevice    58.  4.100 / 58.  4.100
  libavfilter     7. 24.100 /  7. 24.100
  libswscale      5.  2.100 /  5.  2.100
  libswresample   3.  2.100 /  3.  2.100
  libpostproc    55.  2.100 / 55.  2.100

**Comment by xufuji456** [comment]
3.2.4版本
