### ISSUE TITLE
请问支持ffmpeg -i test.mp4 -filter_complex "[0:v]setpts=0.5*PTS[v];[0:a]atempo=2.0[a]" -map "[v]" -map "[a]" test-2.mp4这个倍速的命令吗

### ISSUE THREAD

**Issue by SunPointed** [xufuji456/FFmpegAndroid#117]
FFmpegUtil添加了这个方法执行时native层直接报错，请问下这个命令支持吗
```
public static String[] change4XSpeed(String sourcePath, String output) {
        String cmd = "ffmpeg -i %s -filter_complex \"[0:v]setpts=0.25*PTS[v];[0:a]atempo=2.0,atempo=2.0[a]\" -map \"[v]\" -map \"[a]\" %s";
        cmd = String.format(cmd, sourcePath, output);
        return cmd.split(" ");
    }
```

**Comment by xufuji456** [comment]
支持的，需要去掉双引号
public static String[] change4XSpeed(String sourcePath, String output) {
        String cmd = "ffmpeg -i %s -filter_complex [0:v]setpts=0.25*PTS[v];[0:a]atempo=2.0,atempo=2.0[a] -map [v] -map [a] %s";
        cmd = String.format(cmd, sourcePath, output);
        return cmd.split(" ");
    }
