### ISSUE TITLE
rtsp播放没有声音

### ISSUE THREAD

**Issue by JKXY** [xufuji456/FFmpegAndroid#118]
Could not find codec parameters for stream 1 (Audio: pcm_alaw, 8000 Hz, 1 channels, 64 kb/s): unspecified sample format

不支持pcm音频，可以添加支持吗？

**Comment by xufuji456** [comment]
可以的，迟点我把pcm_alaw编译进去。
你是用在项目上，还是学习用的

**Comment by JKXY** [comment]
嗯呢，目前我是自己研究学习，之前在公司项目上有相关需求折腾过，不过优化效果没你这个好，延迟比较大

**Comment by xufuji456** [comment]
刚刚更新ffmpeg库，支持了pcm_alaw，你试下有没声音

**Comment by JKXY** [comment]
我测试一下，还是不行，还是一样的日志（之前我是参考的这个https://github.com/bilibili/ijkplayer/issues/4559

**Comment by CooperCao** [comment]
我测试了以下，也是没有声音
