### ISSUE TITLE
希望支持屏幕+音频推流

### ISSUE THREAD

**Issue by mafanwei** [xufuji456/FFmpegAndroid#119]
我自己利用了mediacodec实现了屏幕推流，但是不懂如何混流音频

**Comment by xufuji456** [comment]
你是使用rtmp还是rtsp协议推流，或者是自定义私有协议

**Comment by mafanwei** [comment]
rtsp，我利用了codec和audiorecoder实现了音频的录制，但是不知道如何混流推送

**Comment by xufuji456** [comment]
sdp那里加上音频流信息，然后把音频流封装成rtp包
