### ISSUE TITLE
画面拼接合成后视频质量问题

### ISSUE THREAD

**Issue by JustBugFarmer** [xufuji456/FFmpegAndroid#12]
当我把两个视频进行画面合成以后，视频的质量降低了许多，请问下如何保证视频质量的前提下进行合成？

**Comment by xufuji456** [comment]
你可以重新设置视频分辨率、码率试下

**Comment by AndroidKid19** [comment]
> 你可以重新设置视频分辨率、码率试下

怎么设置视频分辨率和码率

**Comment by xufuji456** [comment]
现在更新了接口，支持应用层指定视频的分辨率、码率
