### ISSUE TITLE
作者您好，视频播放黑屏和画面卡住

### ISSUE THREAD

**Issue by liunans** [xufuji456/FFmpegAndroid#122]
作者您好，为什么我裁剪的视频有的会播放一半后黑屏，有的会剩几秒的时候画面卡住但是有声音

**Comment by xufuji456** [comment]
原来是什么格式视频，剪切成什么格式视频

**Comment by liunans** [comment]
抖音下载的视频，mp4格式的，默认使用框架剪切出来的也是mp4格式
源代码是： "ffmpeg -i %s -ss %d -t %d -acodec copy -vcodec copy %s"

**Comment by liunans** [comment]
> 原来是什么格式视频，剪切成什么格式视频

> 原来是什么格式视频，剪切成什么格式视频
抖音下载的视频，mp4格式的，默认使用框架剪切出来的也是mp4格式

**Comment by xufuji456** [comment]
我从抖音下载一个视频剪切没问题
你发视频给我试下 839789740@qq.com

**Comment by xufuji456** [comment]
把-vcodec copy -acodec copy去掉试下

**Comment by xufuji456** [comment]
我刚才试了ffmpeg -i %s -ss %d -t %d  %s，剪切出来的视频正常。
你把-vcodec copy -acodec copy去掉试下
