### ISSUE TITLE
哥，您好。发现一个音频拼接的问题

### ISSUE THREAD

**Issue by WangkeqiangS** [xufuji456/FFmpegAndroid#124]
音频拼接，两个MP3格式的可以正常拼接。
但是 两个wav或者两个m4a就无法正常拼接
拼接出来的时长不对，是第一个音频的时长。
请问这是什么原因？有什么好的解决办法呢？
命令就是您写的格式   ffmpeg -i concat:%s|%s -acodec copy %s

**Comment by xufuji456** [comment]
可以先把两个音频转成mp3，再进行拼接。
我应该在demo写有这样的示例。

**Comment by WangkeqiangS** [comment]
谢谢，已经看到了转码的功能。
但是转码速度较慢，有解决办法吗？

**Comment by xufuji456** [comment]
可以使用libshine库转mp3，效率比libmp3lame快40%左右，但是音质稍微差一点。
同时，开启多线程转码。

**Comment by WangkeqiangS** [comment]
似乎多线程转码并不起作用

**Comment by xufuji456** [comment]
目前是没有对多线程进行处理
