### ISSUE TITLE
关于视频预览

### ISSUE THREAD

**Issue by aylgyfqc** [xufuji456/FFmpegAndroid#125]
关于视频预览，支持网络的视频的滑动小窗口预览吗？
网络mp4格式和m3u8的在线视频

**Comment by xufuji456** [comment]
网络视频预览，一般是请求关键帧缩略图。
用时间戳去请求对应的关键帧。

**Comment by xufuji456** [comment]
网络视频预览，一般是从服务器请求关键帧缩略图。
用时间戳去请求对应的关键帧。
