### ISSUE TITLE
执行命令偶现闪退

### ISSUE THREAD

**Issue by Heber-xu** [xufuji456/FFmpegAndroid#129]
你好，请问你是对ffmpeg的源码做了什么修改吗？用你这个ffmpeg.so库在Android端执行命令行，偶现执行命令闪退的问题。

目前主要用到两个命令:
String command = "ffmpeg -i " + filepath + " -c:a copy -c:v copy -c:s copy " + modifiedFilepath;
String commandStr = "ffmpeg -f concat -safe 0 -i " + compressVideoFilepath + " -c copy " + resultFilepath;

另外想请教下，近一年ffmpeg库的版本是使用的多少的？我现在把你这个ffmpeg.so库替换成了ijkplayer生成的ffmpeg库（主要是复用），来执行第一个命令的时候，发现字幕流的不能正确处理，用你的可以（我司设备上的视频字幕流格式是text，不能微信压缩发送，用你的库结合第一条命令能转成tx3g，但是ijk自带的ffmpeg不行）。

谢谢。

**Comment by xufuji456** [comment]
目前使用FFmpeg版本是4.2，有对源码进行一些修改
