### ISSUE TITLE
No implementation found for java.lang.String com.frank.ffmpeg.FFmpegCmd.handleProbe

### ISSUE THREAD

**Issue by xiang3306** [xufuji456/FFmpegAndroid#131]
No implementation found for java.lang.String com.frank.ffmpeg.FFmpegCmd.handleProbe(java.lang.String[]) (tried Java_com_frank_ffmpeg_FFmpegCmd_handleProbe and Java_com_frank_ffmpeg_FFmpegCmd_handleProbe___3Ljava_lang_String_2)
视频拼接把app里面的逻辑抽成库的形式就报错了，库的包名还是com.frank.ffmpeg，没怎么搞过ndk，大佬能解答一下吗

**Comment by xufuji456** [comment]
你是不是移植到其他项目了，包名不一致

**Comment by xiang3306** [comment]
application是不一样的，但是我放.FFmpegCmd包名还是和之前一样

**Comment by xufuji456** [comment]
把项目结构截图看一下，还有报错的完整信息
