### ISSUE TITLE
media-handle

### ISSUE THREAD

**Issue by JayRichrd** [xufuji456/FFmpegAndroid#132]
请问libmedia-handle.so部分能开源嘛？

**Comment by xufuji456** [comment]
相关代码已开源，在cpp目录下

**Comment by JayRichrd** [comment]
> 相关代码已开源，在cpp目录下

libffmpeg.so是你自己编译FFMpeg的源码生成的动态库嘛？

**Comment by xufuji456** [comment]
是的，项目里有相关shell脚本
