### ISSUE TITLE
其实我想咨询一下。

### ISSUE THREAD

**Issue by the6nnoo** [xufuji456/FFmpegAndroid#135]
是不是demo中已经有的命令是唯一可用的命令？新写的是不能执行的么？
比如，我想把一个raido的音频音量降低，或者是合成的时候 一个设置为0.5 一个设置为1 。
以下是我尝试的命令：
ffmpeg -i %s -filter:a volume=0.5 %s
ffmpeg -i %s -af volume=-3dB %s
ffmpeg -i %s -i %s -filter_complex [0]volume=0.5,pan=2c[a];[1]volume=0.7,pan=2c[b];[a][b]amix=duration=shortest -ac 2 -c:a libmp3lame -q:a 4 %s
ffmpeg -i %s -vol 30 %s
但是都不成功
所以我就有了以上的疑问

**Comment by xufuji456** [comment]
可以自己拼接，FFmpeg是根据一定规则来组合使用的。
