### ISSUE TITLE
滤镜特效选择完mp4文件崩溃

### ISSUE THREAD

**Issue by BlueAirRL** [xufuji456/FFmpegAndroid#137]
**mp4文件格式解析如下：**
解析多媒体格式 dUrstion : 11 SIZe : 301 021 17 bitRate : 20524753 _ _ . _ formatName : moV , mp4 , m4a , 3gp , 392 , mJ 乙 StreamNUm : 2 Width : 1 920 height : 1 080 aspectRatio : p ixelF0rmat : 1 6 : 9 yuVj420p frameRate : 30 Vide0C0deC : avCI sampleRate : 48000 ChannelS : 2 channelLayout : stereo audioCodec : mp4a

**出现的崩溃如下：**
pid: 2847, tid: 2928, name: Thread-2  >>> com.frank.ffmpeg <<<
 signal 6 (SIGABRT), code -6 (SI_TKILL), fault addr --------
     x0   0000000000000000  x1   0000000000000b70  x2   0000000000000006  x3   0000000000000008
     x4   6564206effffffff  x5   0000000000000000  x6   0000000000000080  x7   6b606d7164736d68
     x8   0000000000000083  x9   ffffffffffffffdf  x10  0000000000000000  x11  0000000000000001
     x12  ffffffffffffffff  x13  0000007f5d27d31e  x14  000000000000004e  x15  0000000000000056
     x16  0000007f7d0b3ed0  x17  0000007f7d05d81c  x18  0000000000000001  x19  0000007f5f9054f8
     x20  0000000000000006  x21  0000007f5f905450  x22  0000000000000019  x23  0000007f5d282f40
     x24  0000007f5f6b9000  x25  0000000000010000  x26  0000000000000000  x27  000000000000000a
     x28  000000000000001a  x29  0000007f5f9042d0  x30  0000007f7d05acac
     sp   0000007f5f9042b0  pc   0000007f7d05d824  pstate 0000000060000000
 backtrace:
     #00 pc 000000000006b824  /system/lib64/libc.so (tgkill+8)
     #01 pc 0000000000068ca8  /system/lib64/libc.so (pthread_kill+64)
     #02 pc 0000000000024180  /system/lib64/libc.so (raise+24)
     #03 pc 000000000001cbec  /system/lib64/libc.so (abort+52)
     #04 pc 0000000000635b10  /data/app/com.frank.ffmpeg-1/lib/arm64/libffmpeg.so (sws_setColorspaceDetails+224)

**Comment by xufuji456** [comment]
看起来是不兼容yuvj420p这种像素格式
