### ISSUE TITLE
can you help me ?

### ISSUE THREAD

**Issue by naynu06** [xufuji456/FFmpegAndroid#138]
https://www.youtube.com/watch?v=BKwagY3nuZo&t=56s

Hello, do you know how to make this kind of video?
Play normally for 2 seconds, zoom in for 4 seconds, and do noise processing on the sound.

How to implement these operations in ffmpeg? Can you give me some ideas?

Although I can use Adobe Premiere to edit these effects, I think if I can use ffmpeg to write code to achieve it, it will greatly improve work efficiency. Does anyone know how to achieve it? ?

**Comment by xufuji456** [comment]
On the one hand, you could use FilterGraph to zoom in/out video frames.
On the other hand, noise processing do you mean "noise supress" ? Maybe you should use NS or AEC.
