### ISSUE TITLE
无法添加水印

### ISSUE THREAD

**Issue by shegang** [xufuji456/FFmpegAndroid#14]
demo在arm64-v8a无法运行，缺少so文件，而且在添加水印闪退。请问如何实现支持多种格式的视频文件播放呢

**Comment by xufuji456** [comment]
MP4、flv、avi这些常见格式都支持的

**Comment by xwcsmile** [comment]
请问是如何添加动态时间水印的,FFmpeg拼接后的命令是什么呢

**Comment by xufuji456** [comment]
@shegang 已经添加arm64平台so库，请更新代码测试
