### ISSUE TITLE
我选择音频剪切，然后出现以下提示文件不存在啥意思

### ISSUE THREAD

**Issue by xiaolanbuzaiaixinyi** [xufuji456/FFmpegAndroid#140]
AtomicFileUtils: readFileLines file not exist: android.util.AtomicFile@3823ff0。。。这文件在手机内部存储是可以播放的。。

**Comment by xufuji456** [comment]
我试了不存在文件路径，也是报这个错。你确认下路径有没特殊字符，最好是全英文路径；
另外看下是内置存储还是外置SD卡路径。

**Comment by tiantian520** [comment]
你好，我也遇到文件不存在的问题，FFmpegUtil.addWaterMarkImg传入的文件路径No such file or directory，但我查看/sdcard/test.mp4确实是存在的

**Comment by xufuji456** [comment]
应该是文件路径有空格导致的，已修复，更新源码看看
