### ISSUE TITLE
ffmpeg so 我想要x86 的 需要自己去编译ffmepg 吗 

### ISSUE THREAD

**Issue by jwc793318828** [xufuji456/FFmpegAndroid#141]
ffmpeg so 我想要x86 的 需要自己去编译ffmepg 吗。

**Comment by xufuji456** [comment]
是Android平台的x86库，还是Windows平台的x86库。
如果是Windows的x86库，需要在Windows平台进行编译。
如果是Android的，多添加一个ABI

**Comment by jwc793318828** [comment]
> 如果是Windows的x86库，需要在Windows平台进行编译。

需要android 的x86 跟x86_64 的ffmpeg so . 这需要自己下载ffmpeg 然后编译这两个版本下的so嘛

**Comment by xufuji456** [comment]
是的

**Comment by jwc793318828** [comment]
> 是的

你现在的so 是编译的哪个版本下的ffmpeg呢

**Comment by xufuji456** [comment]
4.2版本
