### ISSUE TITLE
接入穿戴设备中的时候，画面角度不对

### ISSUE THREAD

**Issue by duyiqun** [xufuji456/FFmpegAndroid#142]
RT,作者你好，首先感谢你的作品，想问下，我在realwear的穿戴设备（头戴设备）中使用的时候（里面是Android系统），android系统里的画面是竖着的，但是通过拉流，再推流到服务器，后从电脑段vlc播放出来，画面是横着的了，这个有什么办法解决吗，或者有哪边的参数需要修改？(通过手机进行拉流，推流播放是正常的) 再次感谢你的无私分享 谢谢

**Comment by xufuji456** [comment]
在推流前，把视频帧逆时针旋转90度回来就可以了

**Comment by duyiqun** [comment]
这个是在android代码中处理还是cpp代码里处理的？之前没有接触过这方面知识。

**Comment by duyiqun** [comment]
另外问下，现在项目里有对断线重连这方面的处理吗？

**Comment by xufuji456** [comment]
一般是渲染时处理，如果使用openGL渲染，把纹理坐标旋转90。如果使用TextureView渲染，可直接用TextureView进行旋转
