### ISSUE TITLE
推流断掉后重新推的话，好像会自己断

### ISSUE THREAD

**Issue by duyiqun** [xufuji456/FFmpegAndroid#146]
作者你好，我把你的代码集成进项目，我通过ffmpeg命令，从摄像头（非安卓的）推流到服务器
ffmpeg命令为ffmpeg -r 30 -i rtsp://admin:ks123456@192.168.10.100:554/h264/ch01/sub/av_stream -vcodec libx264 -max_delay 100 -b:v 800k -s 400x300 -f flv -g 5 -b 700000 rtmp://58.210.169.166:1935/live/2

现在的情况的话，是我推流的代码写在activity中，activity退出重进后，没法第二次推流，第一次是可以正常推流的，这样的情况是因为ffmpeg没有完全关闭吗？
我在onDetroy中已经写了，        
if (mHandler != null) {
            mHandler.removeCallbacksAndMessages(null);
        }
        if (ffmpegHandler != null) {
            ffmpegHandler.cancelExecute(true);
        }

请问下大概的原因，谢谢

**Comment by xufuji456** [comment]
应该是没有完全关闭
