### ISSUE TITLE
切片不能加密

### ISSUE THREAD

**Issue by chengchangmu** [xufuji456/FFmpegAndroid#148]
String buildIndex = "ffmpeg -i %s -c copy -map 0 -f segment -segment_list %s -segment_time 3" +
                " -hls_key_info_file %s/key.keyinfo %s/output%%02d.ts";

片切成功了，但示能加密
log有这个提示
2020-11-30 10:31:27.965 20559-20610/com.frank.ffmpeg I/FFmpegCmd: Setting default whitelist 'file,crypto'

**Comment by xufuji456** [comment]
添加 -protocol_whitelist "file,cryto" 试下

**Comment by chengchangmu** [comment]
> 添加 -protocol_whitelist "file,cryto" 试下
还是一样
