### ISSUE TITLE
大佬 我想给视频添加一张图片做封面 怎么做啊

### ISSUE THREAD

**Issue by MusaHao** [xufuji456/FFmpegAndroid#152]
大佬 我想给视频添加一张图片做封面 怎么做啊

**Comment by xufuji456** [comment]
使用这个命令：ffmpeg -i cut.mp4 -i thumb.jpg -map 0 -map 1 -c copy -c: v:1 png -disposition: v:1 attached_pic thumbnail.mp4
这样可以把图片作为关键帧插入视频头部，也就是封面(v和前面:是连在一起，这里发布会变成表情，所以分开)

**Comment by MusaHao** [comment]
### 感谢大哥回复  但是我用了这个命令以后运行报错了  您麻烦帮忙看一下 命令如下
ffmpeg -i /storage/emulated/0/DCIM/Camera/VID_20201210_19333487.mp4 -i /storage/emulated/0/Pictures/1606872098987.jpg -map 0 -map 1 -c copy -c:v:1 png -disposition:v:1 attached_pic /storage/emulated/0/beibang/fengmian1607603354129.mp4

**Comment by MusaHao** [comment]
感谢大哥回复 但是我用了这个命令以后运行报错了 您麻烦帮忙看一下 命令如下

> ffmpeg -i /storage/emulated/0/DCIM/Camera/VID_20201210_19333487.mp4 -i /storage/emulated/0/Pictures/1606872098987.jpg -map 0 -map 1 -c copy -c:v:1 png -disposition:v:1 attached_pic /storage/emulated/0/beibang/fengmian1607603354129.mp4

**Comment by MusaHao** [comment]
感谢作者大大回复 我用了您的命令以后运行出错了 我用的命令如下 
cmd ffmpeg -i /storage/emulated/0/DCIM/Camera/VID_20201210_19333487.mp4 -i /storage/emulated/0/Pictures/1606872098987.jpg -map 0 -map 1 -c copy -c: v:1 png -disposition: v:1 attached_pic /storage/emulated/0/beibang/fengmian1607603354129.mp4

( -c: v:1 png和-disposition: v:1)里的空格我都去掉啦

**Comment by MusaHao** [comment]
感谢作者大大回复 我用了您的命令以后运行出错了 我用的命令如下:
ffmpeg -i /storage/emulated/0/DCIM/Camera/VID_20201210_19333487.mp4 -i /storage/emulated/0/Pictures/1606872098987.jpg -map 0 -map 1 -c copy -c: v:1 png -disposition: v:1 attached_pic /storage/emulated/0/beibang/fengmian1607603354129.mp4

( -c: v:1 png和-disposition: v:1)里的空格我都去掉啦

**Comment by MusaHao** [comment]
解决了 谢谢大哥

**Comment by MusaHao** [comment]
还有个问题大哥 这个命令在有的手机相册里确实显示成我替换的图片了 但是我用qq查看 或者发布到抖音的时候 还是现在原来的封面 是什么原因呀

**Comment by xufuji456** [comment]
有些app取封面可能不是第一帧，而是后面某一关键帧
因为有些视频前面几帧可能是黑色，所以有些app往后面取封面

**Comment by MusaHao** [comment]
如果要避免这种情况 适配所有的软件  让他们的软件获取到咱们的封面都是我们设置的封面   命令该怎么写啊   有好的解决方案吗

**Comment by KupoGu** [comment]
> 如果要避免这种情况 适配所有的软件 让他们的软件获取到咱们的封面都是我们设置的封面 命令该怎么写啊 有好的解决方案吗

用Glide.with(this).setDefaultRequestOptions(
            RequestOptions()
                .frame(1000000)//1秒
                .centerCrop()
        ).load(url).into(imageview) 在videoview上蒙一层图片，播放的时候消失，支持本地和在线视频第一帧的图
