### ISSUE TITLE
关于media-handle 库的问题

### ISSUE THREAD

**Issue by Ace101** [xufuji456/FFmpegAndroid#155]
ninja: error: '../app/build/intermediates/cmake/debug/obj/armeabi-v7a/libmedia-handle.so', missing and no known rule to make it

编译时遇到这个问题，请问下media-handle库要怎么导入

**Comment by xufuji456** [comment]
media-handle库是动态生成的，你看下cmake和lldb是否安装正确

**Comment by Ace101** [comment]
cmake和lldb都正常，是否需要在某处配置一下

**Comment by Ace101** [comment]
CMakeLists.txt的路径改到app路径下，除了需要将build.gradle里的path修改，是否还需要修改别的地方，现在报错是：
 The source directory "/app/src/main/cpp" does not appear to contain CMakeLists.txt.
