### ISSUE TITLE
为什么会编译失败呢?

### ISSUE THREAD

**Issue by zhai3711** [xufuji456/FFmpegAndroid#156]
您好,我运行app模块时出现以下错误,是什么原因造成的呢?
FFmpegAndroid\Live\CMakeLists.txt : C/C++ debug|arm64-v8a : Configuration failed.
Affected Modules: Live, app

**Comment by xufuji456** [comment]
你可以把Live模块(直播)去掉试下，单独看看app模块编译有没问题
