### ISSUE TITLE
我想对ijkplayer播放器 直播rtsp的时候（或者点播的时候）做录像或者截图保存到相册 怎么操作？求大佬告知，是否可以支持rtmp http 

### ISSUE THREAD

**Issue by ILoveLin** [xufuji456/FFmpegAndroid#159]

**Comment by xufuji456** [comment]
截图保存我已经加有接口，录像保存需要获取音视频帧使用muxer封装。

**Comment by ILoveLin** [comment]
需要获取音视频帧使用muxer封装。  是啥意思。。。。

**Comment by masterhellp** [comment]
> 需要获取音视频帧使用muxer封装。 是啥意思。。。。

Android自带的API

**Comment by ILoveLin** [comment]
> 截图保存我已经加有接口，录像保存需要获取音视频帧使用muxer封装。

我指的是,对rtsp rtmp http各种直播流做接流播放,FFmpeg做一个播放器,可以实现实时视频的录制,和截图,我该如何操作?博主

**Comment by xufuji456** [comment]
修改ff_ffplay.c源码，在av_read_frame解封装读取到AVFrame时，使用av_write_frame写音视频帧，保存成文件。
需要注意的是，在录像开始时调用avformat_write_header，录像结束调用av_write_trailer。
