### ISSUE TITLE
请教作者

### ISSUE THREAD

**Issue by howlaa** [xufuji456/FFmpegAndroid#160]
首先非常感谢作者的无私奉献。请教下，因为我现在有这么一个需求。就是可以实现类似微信视频聊天的实时视频聊天。有推流和拉流。在看作者的代码的时候，不是太懂。作者的onLive是实现了拉流，是不是不能推流？而live只有推流，是不是不能拉流，如果实现我上述的功能是不是推流使用作者上面的app+live。拉流使用onlive?看了一圈，作者的项目评价最高。因此决定采用作者的轮子，但因为本人是新手，水平还是比较初级，烦请作者稍指点下。

**Comment by xufuji456** [comment]
不用客气。。。
live是基于RTMP推流，onLive可以基于RTMP或RTSP拉流播放。
推流直播：一般采用RTMP，不过需要RTMP服务器；
视频聊天：一般基于webRTC；

**Comment by howlaa** [comment]
> RTMP

感谢作者的回复。我的领导现在给我的任务就是先实现Android端的FFmpeg的推流与拉流。我是不是可以这么理解，就是说，我可以采用作者live基于RTMP的推流。然后，可以采用onLive，基于RTMP或者RTSP的拉流播放（即使我采用rtmp协议推流，也可以采用rtsp拉流）？还是推流和拉流都必须采用一样的协议？

**Comment by xufuji456** [comment]
推流和拉流的协议是需要一样的

**Comment by howlaa** [comment]
> 推流和拉流的协议是需要一样的

明白了，感谢作者的耐心的指导！

**Comment by howlaa** [comment]
> 不用客气。。。
> live是基于RTMP推流，onLive可以基于RTMP或RTSP拉流播放。
> 推流直播：一般采用RTMP，不过需要RTMP服务器；
> 视频聊天：一般基于webRTC；

再次请教作者一个幼稚的问题。我在作者的onLive下只找到一个RtspLiveActivity。没有找到rtmp的demo。请教一下，是不是这里rtsp和rtmp只是流地址不同。比如一个是private final static String url = "rtmp://58.200.131.2:1935/livetv/hunantv";，一个是 //    private final static String url = "rtsp://184.72.239.149/vod/mp4:，但使用方法都是一样的？因为我是刚入行的新人，可能问的问题比较初级，再次感谢作者的耐心。

**Comment by howlaa** [comment]
> > 不用客气。。。
> > live是基于RTMP推流，onLive可以基于RTMP或RTSP拉流播放。
> > 推流直播：一般采用RTMP，不过需要RTMP服务器；
> > 视频聊天：一般基于webRTC；
> 
> 再次请教作者一个幼稚的问题。我在作者的onLive下只找到一个RtspLiveActivity。没有找到rtmp的demo。请教一下，是不是这里rtsp和rtmp只是流地址不同。比如一个是private final static String url = "rtmp://58.200.131.2:1935/livetv/hunantv";，一个是 // private final static String url = "rtsp://184.72.239.149/vod/mp4:，但使用方法都是一样的？因为我是刚入行的新人，可能问的问题比较初级，再次感谢作者的耐心。

或者说，onLive作为module为主工程所用的demo有没有？哈哈

**Comment by xufuji456** [comment]
rtmp协议也是支持的，已经编译FFmpeg进去支持rtsp/rtmp/http。
内部会根据url的scheme来判断属于哪种协议

**Comment by howlaa** [comment]
> rtmp协议也是支持的，已经编译FFmpeg进去支持rtsp/rtmp/http。
> 内部会根据url的scheme来判断属于哪种协议

终于等到作者大大的回复，给您点个大大赞！就是说，我现在直接照着您那个rtspActivity写，换个rtmp的url的scheme自己会判断是吧。多谢！

**Comment by howlaa** [comment]
> rtmp协议也是支持的，已经编译FFmpeg进去支持rtsp/rtmp/http。
> 内部会根据url的scheme来判断属于哪种协议

还有一个问题，模块live能支持rtsp吗?如果我改了rtsp的url能支持不

**Comment by howlaa** [comment]
作者啊，或者怎么推送RTSP的流，用你的代码
