### ISSUE TITLE
h265编码

### ISSUE THREAD

**Issue by witness123** [xufuji456/FFmpegAndroid#161]
你好，请问你编译的ffmpeg版本支持h265的解码吗，请问怎么编译支持h265编码呢

**Comment by xufuji456** [comment]
目前没支持，需要先编译h265编码器，然后作为插件编译进FFmpeg

**Comment by witness123** [comment]
但是我看解码好像是支持的，解码是默认的吗？请问有编译过相关的h265的编码器吗，有具体的方法吗

**Comment by xufuji456** [comment]
h265解码器(FFmpeg内部支持)已经编译进去，h265编码器需要单独编译，然后作为插件编译进FFmpeg

**Comment by witness123** [comment]
邮件已收到，谢谢
