### ISSUE TITLE
编译失败:More than one file was found with OS independent path 'lib/arm64-v8a/libmp3lame.so'

### ISSUE THREAD

**Issue by jiangkang** [xufuji456/FFmpegAndroid#162]
具体的报错信息如下:
```
* What went wrong:
Execution failed for task ':app:mergeDebugNativeLibs'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
   > More than one file was found with OS independent path 'lib/arm64-v8a/libmp3lame.so'. If you are using jniLibs and CMake IMPORTED targets, see https://developer.android.com/studio/preview/features#automatic_packaging_of_prebuilt_dependencies_used_by_cmake
```

改动项:
1. 将编译版本和target升到了30

**Comment by jiangkang** [comment]
自问自答吧,已经找到问题了.

与NDK版本,编译版本,target都没关系.

因为使用的Android Studio 4.1 , so文件最好不要放到jnilibs文件夹中,不然和CMake同时使用会报错.

解决办法:
在app module的build.gradle文件中添加下面这个配置:
```
    packagingOptions {
        pickFirst "**/libmp3lame.so"
        pickFirst "**/libffmpeg.so"
    }
```

**Comment by ewgcat** [comment]
More than one file was found with OS independent path 'lib/arm64-v8a/libmp3lame.so'. If you are using jniLibs and CMake IMPORTED targets, see https://developer.android.com/studio/preview/features#automatic_packaging_of_prebuilt_dependencies_used_by_cmake
 并没有解决

**Comment by bobo19870225** [comment]
然并卵
