### ISSUE TITLE
一编译就出错，是不是该更新Android Studio的版本了？

### ISSUE THREAD

**Issue by NTEST-la** [xufuji456/FFmpegAndroid#163]
![image](https://user-images.githubusercontent.com/76198691/106991152-9f553a80-67b0-11eb-83e7-d1742a7d8fbd.png)

**Comment by NTEST-la** [comment]
我用的 4.1.1

**Comment by xufuji456** [comment]
应该与版本没关系，你清除缓存重新编译试试

**Comment by YitouQiongdiaosi** [comment]
我也遇到了相同的问题，请问这边是否解决了

**Comment by YitouQiongdiaosi** [comment]
操作如下：
1.提示没有ndk，让我去sdkmanager里下载ndk         安装ndk和cmake插件
2.local.properties内指定ndk路径
然后就出现了相同的问题，尚未有没有解决思路和方案

**Comment by xufuji456** [comment]
你清除缓存clear project试下，或者重启Android Studio

**Comment by xufuji456** [comment]
应该还需要LLDB插件

**Comment by SheepYang1993** [comment]
ndk要使用16.1.4479499版本

**Comment by NTEST-la** [comment]
我一直用 NDK 21.0.6113669，还是不行

**Comment by masterhellp** [comment]
NDK 16.1.4479499的版本， CMake 3.10.2版本 实测成功
