### ISSUE TITLE
作者您好，目前是否支持android11

### ISSUE THREAD

**Issue by xiahuagui** [xufuji456/FFmpegAndroid#164]
作者您好，目前是否支持android11

**Comment by xufuji456** [comment]
可以的，修改targetVesion就可以

**Comment by xiahuagui** [comment]
作者您好，我的意思是指是否支持android11的分区存储

**Comment by xiahuagui** [comment]
> 可以的，修改targetVesion就可以

作者您好，我的意思是指是否支持android11的分区存储

**Comment by xufuji456** [comment]
可以支持分区存储，只要自定义dataSource作为代理给FFmpeg读取就可以

**Comment by xufuji456** [comment]
测试Android11、Android12运行正常的
