### ISSUE TITLE
想要获取音频波形图，但是没有这个滤镜

### ISSUE THREAD

**Issue by SheepYang1993** [xufuji456/FFmpegAndroid#167]
执行`ffmpeg -i %s -filter_complex "showwavespic=s=640x120" -frames:v 1 %s`
提示`FFmpegCmd: No such filter: '"showwavespic'`

**Comment by xufuji456** [comment]
可以使用Android的Visualizer获取：https://developer.android.google.cn/reference/android/media/audiofx/Visualizer?hl=zh-cn
可能是把这个filter编译进FFmpeg，需要重新编译下。
