### ISSUE TITLE
用IjkVideoView 打开rtsp画面的时候，要是出现网络异常的时候，并没有异常的回调，我应该怎么做才能有异常回调

### ISSUE THREAD

**Issue by LinMulberry** [xufuji456/FFmpegAndroid#168]

**Comment by LinMulberry** [comment]
已经设置了 mMediaPlayer.setOnPreparedListener(mPreparedListener);
            mMediaPlayer.setOnVideoSizeChangedListener(mSizeChangedListener);
            mMediaPlayer.setOnCompletionListener(mCompletionListener);
            mMediaPlayer.setOnErrorListener(mErrorListener);
            mMediaPlayer.setOnInfoListener(mInfoListener);
            mMediaPlayer.setOnBufferingUpdateListener(mBufferingUpdateListener);
            mMediaPlayer.setOnSeekCompleteListener(mSeekCompleteListener);
            mMediaPlayer.setOnTimedTextListener(mOnTimedTextListener);，是需要再设置什么参数吗

**Comment by xufuji456** [comment]
在ff_ffplay.c设置interrupt_callback
