### ISSUE TITLE
请问一下，我应该如何获取静音检测的结果

### ISSUE THREAD

**Issue by ChaoCaiGuo** [xufuji456/FFmpegAndroid#169]
你好
请问一下  我应该如何获取静音检测的结果 
调用到的指令是   ffmpeg  -nostats -i 文件.mp3 -af silencedetect=n=-70dB:d=0.7 -f null
我对ffmpeg刚接触很不熟悉 不知道这条指令有没有别的方式来进行保存
在电脑上我使用的是重定向的方式  将结果保存到txt中
ffmpeg  -nostats -i c.mp3 -af silencedetect=n=-70dB:d=0.7 -f null  2>g.txt
在这个库中似乎无法通过该方式进行保存
请问一下 我应该如何来获取结果

**Comment by xufuji456** [comment]
你好，我更新了代码，回调silencedetect的静音检测结果
