### ISSUE TITLE
运行demo无法找到"libmedia-handle.so"

### ISSUE THREAD

**Issue by fansangg** [xufuji456/FFmpegAndroid#170]
java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.frank.ffmpeg-qDKpqTSNGPem3UpfHSGZ_w==/base.apk"],nativeLibraryDirectories=[/data/app/com.frank.ffmpeg-qDKpqTSNGPem3UpfHSGZ_w==/lib/arm64, /data/app/com.frank.ffmpeg-qDKpqTSNGPem3UpfHSGZ_w==/base.apk!/lib/arm64-v8a, /system/lib64, /hw_product/lib64, /system/product/lib64, /prets/lib64]]] couldn't find "libmedia-handle.so"

手机是HUAWEI P30

**Comment by xufuji456** [comment]
你有没修改过代码

**Comment by LittleFogCat** [comment]
同
