### ISSUE TITLE
请教，怎么把cmd命令行集成进去

### ISSUE THREAD

**Issue by luoqqsh** [xufuji456/FFmpegAndroid#175]
作者您好，请教个问题，编译好ffmpeg之后，怎么把cmd命令的东西集成到项目中？

**Comment by xufuji456** [comment]
移植ffmpeg.c源码到项目中，修改main方法为其他方法名(比如run方法)，封装jni方法，传入cmd数组并转换，然后调用run方法执行命令行。

**Comment by jiamclin** [comment]
大神，请问为啥我移植ffmpeg.c后，运行命令行之后，会内存溢出？

**Comment by xufuji456** [comment]
这得看你的命令有多长，分配给命令数组的内存是不是足够大
