### ISSUE TITLE
请问一下，ffmpeg.so有12MB，但是我查看apk里面只有4.6MB，这是什么原因呢？

### ISSUE THREAD

**Issue by tianminggh** [xufuji456/FFmpegAndroid#178]

**Comment by xufuji456** [comment]
在打包apk时，会对so库进行压缩优化；
你解压apk看看有没有so库在libs目录里。

**Comment by tianminggh** [comment]
> 在打包apk时，会对so库进行压缩优化；
> 你解压apk看看有没有so库在libs目录里。

好的  谢谢  我也搜到这篇文章https://www.sunzn.com/2020/06/05/Android-M-%E7%9A%84-NDK-%E8%A1%8C%E4%B8%BA%E5%8F%98%E6%9B%B4%E5%AF%B9-APK-%E5%8C%85%E4%BD%93%E7%A7%AF%E7%9A%84%E5%BD%B1%E5%93%8D/
minSdkVersion升级到23就不会压缩
