### ISSUE TITLE
运行报错

### ISSUE THREAD

**Issue by ZeroMCat** [xufuji456/FFmpegAndroid#18]
![image](https://user-images.githubusercontent.com/24557373/45659501-71abc000-bb27-11e8-873e-61abb7ed6c82.png)

**Comment by xufuji456** [comment]
请问你有没修改为本机音频路径呢，读内存的权限有没给

**Comment by ZeroMCat** [comment]
> 请问你有没修改为本机音频路径呢，读内存的权限有没给

![image](https://user-images.githubusercontent.com/24557373/45730309-82316880-bc03-11e8-901e-a2b035ee11af.png)
你好，我是将这个路径放到了本地raw文件中

**Comment by ZeroMCat** [comment]
> 请问你有没修改为本机音频路径呢，读内存的权限有没给
![image](https://user-images.githubusercontent.com/24557373/45730354-bc026f00-bc03-11e8-9172-b601829cbcc6.png)

**Comment by xufuji456** [comment]
你把这两个文件拷贝到手机内存根目录试下，可能ffmpeg无法读取本地raw文件

**Comment by ZeroMCat** [comment]
大哥，又来麻烦你了，音频混合的时候走完了，但是混合出来的文件是0kb。也没得任何的提示log

**Comment by xufuji456** [comment]
你混音的两个音频文件什么格式的呢，采样率多少
