### ISSUE TITLE
请问一下，在播放rtsp直播流的情况下，怎么去做软件变焦呢

### ISSUE THREAD

**Issue by always025** [xufuji456/FFmpegAndroid#186]

**Comment by xufuji456** [comment]
变什么焦，是摄像头对焦吗

**Comment by always025** [comment]
不好意思,之前没有理清需求,需求是不通过摄像头,而是拉到视频流之后,对每帧图片去做裁剪,不知道这个有没有办法实现呢?因为拉不到你修改之后的Ijkplayer的源码

**Comment by xufuji456** [comment]
可以的，在ijkplayer的ff_play.c代码里，视频帧解码后可以做剪裁、滤镜

**Comment by always025** [comment]
主要是看你在博客上看,不知道你这边是修改了哪些地方,能不能提供一下,你优化后的源码呢

**Comment by xufuji456** [comment]
修改的源码没有保存
