### ISSUE TITLE
能提供一下 FFmpeg mediacodec 硬解码相关代码么？

### ISSUE THREAD

**Issue by Enoch-Liu** [xufuji456/FFmpegAndroid#189]
我尝试过两种方法，均不能成功。
第一种是参考 ffmpeg 官方 examples 中的 hw_decode.c，运行时在 avcodec_get_hw_config 时不成功。
第二种是参考网上的一种说法，avcodec_find_decoder_by_name("h264_mediacodec") ，然后其他跟软解差不多。这种方法在某些机器上（小米 Mix2S）会有个提示称 I/ExtendedACodec: Decoder will be in frame by frame mode。在 小米 11 上不会有这个提示。但在这两款手机上，都不能连续解码。也就是说，解码获得一帧解码后的数据后，再次将 packet 送入解码器时会返回 -11 （EAGAIN）。将解码后的数据保存下来看，Mix2S 拿到的是 NV12 数据，但通过工具 7yuv 读取时只有两块颜色不一样的绿色矩形。Mi 11 拿到的好像是一个 yuv420p 的数据，具体没细看。

**Comment by xufuji456** [comment]
首先要确认，这个视频是否支持硬解，不同手机的硬解表现可能不同。

**Comment by xufuji456** [comment]
mediacodec硬解出来可能是NV12，也可能是YUV420P。需要用pixel_fmt判断，如果不是YUV420P，需要进行色彩空间转换，否则出现你描述的绿色块。
