### ISSUE TITLE
项目编译问题

### ISSUE THREAD

**Issue by angloser** [xufuji456/FFmpegAndroid#191]
运行项目总是报错  More than one file was found with OS independent path 'lib/arm64-v8a/libmp3lame.so'.If you are using jniLibs and CMake IMPORTED targets, see https://developer.android.com/studio/preview/features#automatic_packaging_of_prebuilt_dependencies_used_by_cmake

**Comment by xufuji456** [comment]
你是直接下载代码，还是git clone的

**Comment by billzbh** [comment]
> 运行项目总是报错 More than one file was found with OS independent path 'lib/arm64-v8a/libmp3lame.so'.If you are using jniLibs and CMake IMPORTED targets, see https://developer.android.com/studio/preview/features#automatic_packaging_of_prebuilt_dependencies_used_by_cmake

packagingOptions {
        //防止裁剪优化
        //doNotStrip "**/*.so"
        //解决gradle BUG. 优先选择JNILIBS下的so库
        pickFirst 'lib/arm64-v8a/libmp3lame.so'
}
