### ISSUE TITLE
模拟器运行推流的时候闪退

### ISSUE THREAD

**Issue by angel-baal** [xufuji456/FFmpegAndroid#192]
错误码：I/PushActivity: filePath=storage/emulated/0/1.mp4
    liveUrl=rtmp://192.168.1.104/live/stream
A/libc: Fatal signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0xffff0ffc in tid 9775 (Thread-2), pid 9731 (om.frank.ffmpeg)

**Comment by xufuji456** [comment]
建议使用真机测试
