### ISSUE TITLE
请问可以调用哪个方法可以将每一帧编码并保存成视频文件？

### ISSUE THREAD

**Issue by littleredcap** [xufuji456/FFmpegAndroid#198]
`@override
public void onPreviewFrame(byte[] perframe, int width, int height, int rotation, int fmt, long tsInNanoTime){

}`
摄像头捕获到的每一帧都会回调这个方法，请问调用那个方法可以将每一帧编码并保存成视频文件？

**Comment by xufuji456** [comment]
这个是录像功能，在Android系统有MediaRecorder直接录像。

**Comment by xufuji456** [comment]
或者，使用Mediacodec编码成h264，再使用mediamuxer封装成mp4格式
(预览帧一般是NV21或NV12，需要编码成h264)
