### ISSUE TITLE
avcodec_receive_frame永远返回EAGAIN

### ISSUE THREAD

**Issue by 283958849** [xufuji456/FFmpegAndroid#199]
我看你用的ffmpeg还是比较老的，我在使用最新ffmpeg4.4的时候，MediaCodec硬解码H264码流时，avcodec_receive_frame永远返回EAGAIN，有什么调试建议吗：
1，文件码流没问题，用其他播放器播放正常；
2，我有循环喂数据；
3，换成软解码则顺利结束，硬解码就不行

感谢大佬！

**Comment by xufuji456** [comment]
我使用的是4.2版本。
可能是硬解码不支持，
使用硬解前先用width、height、framerate、profile、level等参数判断是否支持。
