### ISSUE TITLE
大佬，请问一个问题。

### ISSUE THREAD

**Issue by ELEVENEV** [xufuji456/FFmpegAndroid#2]
视频源有一点点的晃动，视频转码保存下来的视频就会出现很马赛克，视频播放也是一样，这个要怎么优化处理，应该怎么改呢，大神有什么高见。

**Comment by xufuji456** [comment]
这是由于转码时，产生方块效应导致的，这些方块也就是马赛克，加上视频的环路滤波后应该可以去除方块。

**Comment by ELEVENEV** [comment]
问您要一下您把FFmpeg 和fdk-aac 和x264合并成一个so库的shell是怎么写的呀。方便教一下吗，如果方便的可以发给我吗，谢谢了。1836777832@qq.om

**Comment by xufuji456** [comment]
@wxh12138  你好，FFmpeg源码包含aac和x264功能模块的，FFmpeg编译成so库只要enable开关。
如果只使用aac和x264，不用到FFmpeg的其他库，那么单独使用aac、x264模块编译。

**Comment by ELEVENEV** [comment]
那您合并成一个so库的shell文件可以发一份给我吗，

**Comment by xufuji456** [comment]
相关编译步骤与脚本已发送到你的邮箱。需要注意的是，编译环境是Linux环境。

**Comment by ELEVENEV** [comment]
您发的是1836777832@qq.com这个邮箱吗，

**Comment by wxh12138** [comment]
我上面打错了，555 大佬能在发一次吗。

**Comment by xufuji456** [comment]
你的邮箱多少，555是什么呢

**Comment by ELEVENEV** [comment]
拜托了，请你在发一次到我这个邮箱1836777832@qq.com，上面我手残  少打了一个c

**Comment by xufuji456** [comment]
噢，重新发送了
