### ISSUE TITLE
android studio 4.2.2 编译出错

### ISSUE THREAD

**Issue by Staticzll** [xufuji456/FFmpegAndroid#200]
android studio 4.2.2 编译出错
Execution failed for task ':libmp3:mergeDebugNativeLibs'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.MergeJavaResWorkAction
   > 2 files found with path 'lib/armeabi-v7a/libmp3lame.so' from inputs:
      - D:\AndroidStudioProjects\FFmpegAndroid\libmp3\build\intermediates\merged_jni_libs\debug\out
      - D:\AndroidStudioProjects\FFmpegAndroid\libmp3\build\intermediates\cmake\debug\obj
     If you are using jniLibs and CMake IMPORTED targets, see

**Comment by xufuji456** [comment]
你更新代码试下，是mp3lame库重复导致的
