### ISSUE TITLE
I can't reuse command

### ISSUE THREAD

**Issue by KiwanPark** [xufuji456/FFmpegAndroid#201]
Hi xufuji456.

I really thank you for your hard work.

I have a problem.

I want to know multi-files info, ffProbe.

It can be work just one time - 1 file

How to print multi file in ffProbe?

this is my code.

val commandLine =
                "ffprobe -v quiet -print_format json -show_format -show_streams $inputPath".split(
                 " "
                ).toTypedArray()

ffmpegHandler!!.executeFFprobeCmdWithCallBack(commandLine)

any file print info at first time - first file.

Thank you for reading and my terrible english skill.

**Comment by xufuji456** [comment]
Hello, friend:
    As I know, ffprobe can only print a file at a time.
You can call it one by one if you need to print multi files.
Each time, it will return a json string as result.
