### ISSUE TITLE
No such file or directory

### ISSUE THREAD

**Issue by fuchangle** [xufuji456/FFmpegAndroid#202]
文件夹命名有空格的时候(如下：Screen recordings)，native会返回文件找不到
ffmpeg指令：ffmpeg -ss 6.000000 -accurate_seek -t 28.000000 -i /storage/emulated/0/DCIM/Screen recordings/Screen_Recording_20211124-155332_One UI Home.mp4 -map 0 ...

错误日志：/storage/emulated/0/DCIM/Screen: No such file or directory
from native msg=/storage/emulated/0/DCIM/Screen: No such file or directory

**Comment by xufuji456** [comment]
修复了文件路径有空格问题，更新代码看看
