### ISSUE TITLE
预览画面和播放画面显示问题

### ISSUE THREAD

**Issue by BeaHugs** [xufuji456/FFmpegAndroid#206]
你好,我在使用实时直播推流时发现, 预览画面和实时推流直播显示画面方向不一致是什么原因

**Comment by BeaHugs** [comment]
不是镜像问题, 预览画面是竖屏,播放画面就变成了横屏

**Comment by xufuji456** [comment]
修复了竖屏推流问题，需要把yuv数据旋转90度

**Comment by liangweihao** [comment]
> 修复了竖屏推流问题，需要把yuv数据旋转90度

大佬 这个问题提交了吗 视频滤镜 加载的视频也是横竖屏是相反的
