### ISSUE TITLE
视频剪切后，质量下降明显

### ISSUE THREAD

**Issue by wangjian-k** [xufuji456/FFmpegAndroid#21]
使用视频剪切功能后，质量有很大程度下降，看了下ffmpeg的命令为：ffmpeg -i %s -ss %d -t %d %s， 试过改为：ffmpeg -i %s -vcodec copy -acodec copy -ss %d -t %d %s， 保留原有的编码格式进行剪切，但是ffmpeg.c中会报错，具体还没看明白，请问作者大佬知道什么原因吗？ 是因为ffmpeg.so内部包含的功能不完善导致的么？ 我在pc上直接使用ffmpeg -i %s -ss %d -t %d %s命令进行剪切，质量不会有降低的。

**Comment by xufuji456** [comment]
你好，原来指定是MP4输出格式的原因
现在，改为视频剪切输出格式与输入格式保持一致， 且 -vcodec copy -acodec copy
请更新最新版本代码
