### ISSUE TITLE
在Windows平台下copy cpp目录下的文件编译出错

### ISSUE THREAD

**Issue by pengcao1** [xufuji456/FFmpegAndroid#210]
7 warnings generated.
  [2/2] Linking CXX shared library ..\..\..\..\build\intermediates\cmake\devDebug\obj\armeabi-v7a\libmedia-handle.so
  FAILED: ../../../../build/intermediates/cmake/devDebug/obj/armeabi-v7a/libmedia-handle.so
  cmd.exe /C "cd . && D:\SDK\ndk\21.0.6113669\toolchains\llvm\prebuilt\windows-x86_64\bin\clang++.exe --target=armv7-none-linux-androideabi23 --gcc-toolcha
in=D:/SDK/ndk/21.0.6113669/toolchains/llvm/prebuilt/windows-x86_64 --sysroot=D:/SDK/ndk/21.0.6113669/toolchains/llvm/prebuilt/windows-x86_64/sysroot -fPIC
-g -DANDROID -fdata-sections -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -D_FORTIFY_SOURCE=2 -march=armv7-a -mthumb
 -Wformat -Werror=format-security   -std=gnu++11 -O0 -fno-limit-debug-info  -Wl,--exclude-libs,libgcc_real.a -Wl,--exclude-libs,libatomic.a -static-libstdc
++ -Wl,--build-id -Wl,--fatal-warnings -Wl,--exclude-libs,libunwind.a -Wl,--no-undefined -Qunused-arguments -shared -Wl,-soname,libmedia-handle.so -o ..\..
\..\..\build\intermediates\cmake\devDebug\obj\armeabi-v7a\libmedia-handle.so CMakeFiles/media-handle.dir/src/main/cpp/ffmpeg/cmdutils.c.o CMakeFiles/media-
handle.dir/src/main/cpp/ffmpeg/ffmpeg.c.o CMakeFiles/media-handle.dir/src/main/cpp/ffmpeg/ffmpeg_filter.c.o CMakeFiles/media-handle.dir/src/main/cpp/ffmpeg
/ffmpeg_opt.c.o CMakeFiles/media-handle.dir/src/main/cpp/ffmpeg_cmd.c.o CMakeFiles/media-handle.dir/src/main/cpp/ffmpeg/ffprobe.c.o CMakeFiles/media-handle
.dir/src/main/cpp/ffmpeg/ffmpeg_hw.c.o CMakeFiles/media-handle.dir/src/main/cpp/audio_player.cpp.o CMakeFiles/media-handle.dir/src/main/cpp/opensl_audio_pl
ayer.cpp.o CMakeFiles/media-handle.dir/src/main/cpp/video_player.cpp.o CMakeFiles/media-handle.dir/src/main/cpp/ffmpeg_pusher.cpp.o CMakeFiles/media-handle
.dir/src/main/cpp/video_filter.c.o CMakeFiles/media-handle.dir/src/main/cpp/ffprobe_cmd.cpp.o CMakeFiles/media-handle.dir/src/main/cpp/cut_video.cpp.o CMak
eFiles/media-handle.dir/src/main/cpp/visualizer/fft.cpp.o CMakeFiles/media-handle.dir/src/main/cpp/visualizer/fixed_fft.cpp.o CMakeFiles/media-handle.dir/s
rc/main/cpp/visualizer/block_queue.c.o CMakeFiles/media-handle.dir/src/main/cpp/visualizer/frank_visualizer.cpp.o CMakeFiles/media-handle.dir/src/main/cpp/
visualizer/frank_visualizer_jni.cpp.o CMakeFiles/media-handle.dir/src/main/cpp/visualizer/window.cpp.o CMakeFiles/media-handle.dir/src/main/cpp/metadata/me
dia_retriever.cpp.o CMakeFiles/media-handle.dir/src/main/cpp/metadata/media_retriever_jni.cpp.o CMakeFiles/media-handle.dir/src/main/cpp/metadata/metadata_
util.c.o CMakeFiles/media-handle.dir/src/main/cpp/metadata/ffmpeg_media_retriever.c.o  ../../../../libs/armeabi-v7a/libffmpeg.so -landroid -ljnigraphics -l
OpenSLES -llog -latomic -lm && cd ."
  ../../../../src/main/cpp/ffmpeg/cmdutils.c:714: error: undefined reference to 'av_mallocz_array'
  ../../../../src/main/cpp/ffmpeg/cmdutils.c:1309: error: undefined reference to 'av_muxer_iterate'
  ../../../../src/main/cpp/ffmpeg/cmdutils.c:1323: error: undefined reference to 'av_demuxer_iterate'
  ../../../../src/main/cpp/ffmpeg/cmdutils.c:1658: error: undefined reference to 'av_bsf_iterate'
  ../../../../src/main/cpp/ffmpeg/cmdutils.c:1696: error: undefined reference to 'av_filter_iterate'
  ../../../../src/main/cpp/ffmpeg/cmdutils.c:2142: error: undefined reference to 'av_mallocz_array'
  ../../../../src/main/cpp/ffmpeg/cmdutils.c:1445: error: undefined reference to 'avcodec_get_hw_config'
  ../../../../src/main/cpp/ffmpeg/cmdutils.c:1448: error: undefined reference to 'avcodec_get_hw_config'
  ../../../../src/main/cpp/ffmpeg/cmdutils.c:1451: error: undefined reference to 'av_hwdevice_get_type_name'
  ../../../../src/main/cpp/ffmpeg/ffmpeg.c:3505: error: undefined reference to 'av_buffersink_get_hw_frames_ctx'
  ../../../../src/main/cpp/ffmpeg/ffmpeg.c:3506: error: undefined reference to 'av_buffersink_get_hw_frames_ctx'
  ../../../../src/main/cpp/ffmpeg/ffmpeg.c:3507: error: undefined reference to 'av_buffersink_get_format'
  ../../../../src/main/cpp/ffmpeg/ffmpeg.c:3508: error: undefined reference to 'av_buffersink_get_hw_frames_ctx'
  ../../../../src/main/cpp/ffmpeg/ffmpeg.c:2835: error: undefined reference to 'avcodec_get_hw_config'

**Comment by xufuji456** [comment]
库文件没有引用进去
