### ISSUE TITLE
hello,I have some problems with this command, is it because of the version?

### ISSUE THREAD

**Issue by xuboot** [xufuji456/FFmpegAndroid#217]
![image](https://user-images.githubusercontent.com/54123895/188534072-318ddc28-4a1b-4187-898a-1a231b1b7edf.png)
but,windows
![image](https://user-images.githubusercontent.com/54123895/188534229-fc299bf1-671e-4c2c-a456-0641407cde13.png)

**Comment by xufuji456** [comment]
Because there are two acodec you assign, libmp3lame and pcm_s16le.
So, FFmpeg don't know should use which acodec.
Just use pcm_s16le is enough.
