### ISSUE TITLE
Flashback occurs to one module

### ISSUE THREAD

**Issue by PinLeung** [xufuji456/FFmpegAndroid#218]
When I try to splice two audio, I prompt media handler So does not exist. But I overflow the System of FFmpegCmd When loading Library ("media handle") fragments, so error will be prompted。

**Comment by PinLeung** [comment]
No implementation found for int com.frank.ffmpeg.FFmpegCmd.handle(java.lang.String[]) (tried Java_com_frank_ffmpeg_FFmpegCmd_handle and Java_com_frank_ffmpeg_FFmpegCmd_handle___3Ljava_lang_String_2)

**Comment by xufuji456** [comment]
Maybe you move to yourself project, should change the package name of JNI method

**Comment by PinLeung** [comment]
Thankes！Yee,I'm really tired of this mistake. After that, I downloaded your moudle and the compilation failed. It seems that an error occurred in the ndk. I tried to reduce the ndk from 21 to 20, but the method error of the ndk still occurred.Are there any guiding articles in this regard.

**Comment by xufuji456** [comment]
You could take a look at this [https://blog.csdn.net/u011686167/article/details/124132719](url)

**Comment by xufuji456** [comment]
I has fixed this problem. 
You can update and try again.
