### ISSUE TITLE
“rtmp推流直播”打开异常，缺少liblive.so

### ISSUE THREAD

**Issue by fake985** [xufuji456/FFmpegAndroid#219]
![QQ截图20221028153025](https://user-images.githubusercontent.com/61674553/198529788-02016440-a419-4a68-a405-1f255ef6e417.jpg)
![QQ截图20221028152954](https://user-images.githubusercontent.com/61674553/198529808-981d47c9-595b-4cc9-af4d-478e9ae68d15.jpg)

**Comment by invokerhaung** [comment]
把live模块 build.gradle 里ndk armeabi-v7a 的注释去了。重新编译。

**Comment by ningift** [comment]
来信已收到，谢谢。
