### ISSUE TITLE
在线直播的音频流地址和视频流地址可以通过此FFmpegAndroid  合成一路直播流(音视频流),再用播放器播放吗?

### ISSUE THREAD

**Issue by ILoveLin** [xufuji456/FFmpegAndroid#225]
目前条件:有视频流地址,有该视频流相对于的音频流地址
功能需求:把音频流和视频流合成一路音视频流,然后用vlc(或者其他播放器)播放

FFmpegAndroid  能够合成一路音视频流地址,吗?合成之后我在本地app 播放器(vlc)可以播放出来吗?

**Comment by xufuji456** [comment]
可以合成
