### ISSUE TITLE
直播推流3次才能正常推流

### ISSUE THREAD

**Issue by weasen** [xufuji456/FFmpegAndroid#228]
# 直播推流功能,对应apk提示
只有第三次可以成功推流.

1. 点击第一次提示:
```shell
error of RTMP sending packet
server 应答:  is publishing to path 'live/stream', 1 track (MPEG4-audio)
```
2. 点击第二次提示:
```
error of RTMP sending packet
server 应答: is publishing to path 'live/stream', 2 tracks (H264, MPEG4-audio)
```
3. 点击第三次提示:
```
无提示,正常
server 应答: is publishing to path 'live/stream', 2 tracks (H264, MPEG4-audio)
```
> server使用的是https://github.com/aler9/mediamtx/releases  mediamtx_v0.22.0_linux_armv7.tar.gz版本

下面为3次启动的独立log日志:
[log1.txt](https://github.com/xufuji456/FFmpegAndroid/files/11168002/log1.txt)
[log2.txt](https://github.com/xufuji456/FFmpegAndroid/files/11168001/log2.txt)
[log3.txt](https://github.com/xufuji456/FFmpegAndroid/files/11167998/log3.txt)

请帮忙查看下,谢谢!!!

**Comment by weasen** [comment]
使用的是[ZLMediaKit](https://github.com/ZLMediaKit/ZLMediaKit) 服务器

**Comment by xufuji456** [comment]
推流到srs服务器看看
