### ISSUE TITLE
请教个问题 关于c++

### ISSUE THREAD

**Issue by wnpllrzodiac** [xufuji456/FFmpegAndroid#23]
修改ffmpeg代码main函数
其中有部分的代码涉及到调用 exit_program 退出程序的作用。
但是java调用ffmepg转码，不能调用，负责导致app闪退。
简单注释掉 exit() 并不能解决问题。
当输入文件不存在，或者指定的codec 名有问题的时候，原函数逻辑是通过exit() 直接退出程序，跳过下面的函数执行。但是android端需要一种类似的机制，做到跳出ffmpegmain() 主函数
望解答，谢谢！

```
void exit_program(int ret)
{
    if (program_exit)
        program_exit(ret);

    exit(ret);
}
```

**Comment by xufuji456** [comment]
android退出进程，可以使用android.os.Process.killProcess(Process.myPid());

**Comment by wnpllrzodiac** [comment]
你的意思是改写 exit_program函数，调用 java结束自己？
