### ISSUE TITLE
修改元数据

### ISSUE THREAD

**Issue by fywalll** [xufuji456/FFmpegAndroid#232]
使用了命令行修改元数据可以成功，但是非常慢
100M左右的视频大概需要30分钟，看日志发现是把所有的时间点都修改了
命令行：ffmpeg -i input.mp4 -metadata artist=ceshi output.mp4

查看文档说有只修改1帧的，可是试了也不管用，还是修改的所有时间段的视频
[ ffmpeg -i INPUT -metadata:s:a:0 language=eng OUTPUT](https://ffmpeg.org/ffmpeg.html)

我的理解视频文件的元数据只是在指定的文件区域里，不用所有的时间段都进行修改

**Comment by fywalll** [comment]
ffmpeg -i INPUT -metadata:s:a:0 language=eng OUTPUT
这是文档给的例子

**Comment by xufuji456** [comment]
加上 -codec copy 看看
