### ISSUE TITLE
转码6k分辨率视频闪退

### ISSUE THREAD

**Issue by empty56631** [xufuji456/FFmpegAndroid#235]
我这里有一段长度5s左右的h265的6k分辨率的视频 我想把他专成h264的视频 但是发现转码的过程中闪退，我发现在转码的过程中app内存不断变大，闪退的原因疑似是内存溢出造成的请问是为什么 有什么办法可以避免这个问题？

**Comment by empty56631** [comment]
这是我转码用到的命令行
ffmpeg -y -i input.mov -c:v libx264 -preset ultrafast -crf 23 -c:a copy output.mov

**Comment by xufuji456** [comment]
崩溃日志发出来，测试视频也发出来

**Comment by empty56631** [comment]
logcat并没有明确的崩溃信息 这是崩溃时我唯一能捕捉到的log [https://raw.githubusercontent.com/programmerauthor/Storage/main/source/241688638613_.pic.jpg](url)

测试视频在这里
[https://media.githubusercontent.com/media/programmerauthor/Storage/main/source/input.mov](url)
