### ISSUE TITLE
1、你集成到项目里，可以拷贝so使用，也可以使用cpp源码；

### ISSUE THREAD

**Issue by hdProj** [xufuji456/FFmpegAndroid#236]
拷贝so文件到项目，也把cpp文件拷贝过去了，还是会提示如下错误，请问是什么原因导致的呢，是不是so文件影响的？
 java.lang.UnsatisfiedLinkError: No implementation found for int com.frank.ffmpeg.FFmpegCmd.handle(java.lang.String[]) (tried Java_com_frank_ffmpeg_FFmpegCmd_handle and Java_com_frank_ffmpeg_FFmpegCmd_handle___3Ljava_lang_String_2)

_Originally posted by @xufuji456 in https://github.com/xufuji456/FFmpegAndroid/issues/33#issuecomment-451076661_

**Comment by xufuji456** [comment]
你有没接触过JNI开发，这是JNI通用问题

**Comment by hdProj** [comment]
已经解决，谢谢博主

**Comment by xufuji456** [comment]
不用客气
