### ISSUE TITLE
ffmpeg滤镜时打开声音播放视频，声音和视频画面都会卡顿

### ISSUE THREAD

**Issue by zhongyuanceshi** [xufuji456/FFmpegAndroid#246]
使用最新代码测试ffmpeg滤镜功能时发现播放视频时声音和视频画面都会卡顿，关闭声音后视频画面不卡顿。尝试在线程中播放声音还是会卡顿(原代码没有在线程中)

**Comment by xufuji456** [comment]
滤镜比较耗时，建议加线程处理
