### ISSUE TITLE
操作失败的错误信息能否上抛给java

### ISSUE THREAD

**Issue by ChasingWord** [xufuji456/FFmpegAndroid#251]
目前只会返回执行结果，int类型，执行失败的错误信息没有上抛出来，只是进行了log打印
如果是内存不足，需要提示用户，但java拿不到错误信息
看了是这个方法有进行log打印错误信息：
ffmpeg_mux.c文件：
`
int mux_check_init(Muxer *mux)
{
    if (ret < 0) {
        av_log(mux, AV_LOG_ERROR, "Could not write header (incorrect codec "
               "parameters ?): %s\n", av_err2str(ret));
        return ret;
    }
}
`
不会写c，作者能否有空的时候，帮忙把错误信息上抛到java层

**Comment by xufuji456** [comment]
错误信息已回调到FFmpegCmd.java的onMsgCallback方法
