### ISSUE TITLE
Android系统适配问题，闪退

### ISSUE THREAD

**Issue by Cemetery159** [xufuji456/FFmpegAndroid#26]
java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.quxue.newtalk.student-uPYh3stFaywpHrBrVpCecQ==/base.apk", zip file "/data/app/com.quxue.newtalk.student-uPYh3stFaywpHrBrVpCecQ==/split_lib_dependencies_apk.apk", zip file "/data/app/com.quxue.newtalk.student-uPYh3stFaywpHrBrVpCecQ==/split_lib_resources_apk.apk", zip file "/data/app/com.quxue.newtalk.student-uPYh3stFaywpHrBrVpCecQ==/split_lib_slice_0_apk.apk", zip file "/data/app/com.quxue.newtalk.student-uPYh3stFaywpHrBrVpCecQ==/split_lib_slice_1_apk.apk", zip file "/data/app/com.quxue.newtalk.student-uPYh3stFaywpHrBrVpCecQ==/split_lib_slice_2_apk.apk", zip file "/data/app/com.quxue.newtalk.student-uPYh3stFaywpHrBrVpCecQ==/split_lib_slice_3_apk.apk", zip file "/data/app/com.quxue.newtalk.student-uPYh3stFaywpHrBrVpCecQ==/split_lib_slice_4_apk.apk", zip file "/data/app/com.quxue.newtalk.student-uPYh3stFaywpHrBrVpCecQ==/split_lib_slice_5_apk.apk", zip file "/data/app/com.quxue.newtalk.student-uPYh3stFaywpHrBrVpCecQ==/split_lib_slice_6_apk.apk", zip file "/data/app/com.quxue.newtalk.student-uPYh3stFaywpHrBrVpCecQ==/split_lib_slice_7_apk.apk", zip file "/data/app/com.quxue.newtalk.student-uPYh3stFaywpHrBrVpCecQ==/split_lib_slice_8_apk.apk", zip file "/data/app/com.quxue.newtalk.student-uPYh3stFaywpHrBrVpCecQ==/split_lib_slice_9_apk.apk"],nativeLibraryDirectories=[/data/app/com.quxue.newtalk.student-uPYh3stFaywpHrBrVpCecQ==/lib/arm64, /data/app/com.quxue.newtalk.student-uPYh3stFaywpHrBrVpCecQ==/base.apk!/lib/arm64-v8a, /data/app/com.quxue.newtalk.student-uPYh3stFaywpHrBrVpCecQ==/split_lib_dependencies_apk.apk!/lib/arm64-v8a, /data/app/com.quxue.newtalk.student-uPYh3stFaywpHrBrVpCecQ==/split_lib_resources_apk.apk!/lib/arm64-v8a, /data/app/com.quxue.newtalk.student-uPYh3stFaywpHrBrVpCecQ==/split_lib_slice_0_apk.apk!/lib/arm64-v8a, /data/app/com.quxue.newtalk.student-uPYh3stFaywpHrBrVpCecQ==/split_lib_slice_1_apk.apk!/lib/arm64-v8a, /data/app/com.quxue.newtalk.student-uPYh3stFaywpHrBrVpCecQ==/split_lib_slice_2_apk.apk!/lib/arm64-v8a, /data/app/com.quxue.newtalk.student-uPYh3stFaywpHrBrVpCecQ==/split_lib_slice_3_apk.apk!/lib/arm64-v8a, /data/app/com.quxue.newtalk.student-uPYh3stFaywpHrBrVpCecQ==/split_lib_slice_4_apk.apk!/lib/arm64-v8a, /data/app/com.quxue.newtalk.student-uPYh3stFaywpHrBrVpCecQ==/split_lib_slice_5_apk.apk!/lib/arm64-v8a, /data/app/com.quxue.newtalk.student-uPYh3stFaywpHrBrVpCecQ==/split_lib_slice_6_apk.apk!/lib/arm64-v8a, /data/app/com.quxue.newtalk.student-uPYh3stFaywpHrBrVpCecQ==/split_lib_slice_7_apk.apk!/lib/arm64-v8a, /data/app/com.quxue.newtalk.student-uPYh3stFaywpHrBrVpCecQ==/split_lib_slice_8_apk.apk!/lib/arm64-v8a, /data/app/com.quxue.newtalk.student-uPYh3stFaywpHrBrVpCecQ==/split_lib_slice_9_apk.apk!/lib/arm64-v8a, /system/lib64, /vendor/lib64]]] couldn't find "libmedia-handle.so"

**Comment by xufuji456** [comment]
缺少arm64-v8a的so库，后续补充上去
