### ISSUE TITLE
解码播放ape音乐发生错误

### ISSUE THREAD

**Issue by tangmingscau** [xufuji456/FFmpegAndroid#27]
我使用你的demo去播放ape音乐，声音输出异常，音乐跳跃式播放。我按照你的demo，使用ffmpeg 3.4版本写一个播放音乐的demo，其他音乐文件正常输出，ape音乐播放发生错误，声音输出异常
int ret = avcodec_send_packet(avCodecContext, avPacket);
错误码是-11，查阅了很多资料都不知道这个是什么错误，想去看ffmpeg源码，也不知道如何看错误码对上的具体原因。大神可以给点意见吗？

**Comment by xufuji456** [comment]
请把ape文件发给我看下，邮箱839789740@qq.com
