### ISSUE TITLE
demo运行

### ISSUE THREAD

**Issue by 469065768** [xufuji456/FFmpegAndroid#3]
你好，运行你的demo在魅族nate3 note上，ffmpeg异常
日志信息：
04-20 18:43:25.753 2445-2595/com.frank.ffmpeg A/libc: Fatal signal 11 (SIGSEGV), code 1, fault addr 0x18 in tid 2595 (Thread-606)
04-20 18:43:25.757 364-364/? E/AudioPolicyManager: mapVoiceVoltoCustomVol 10447 Error : dMaxIndex = -1
04-20 18:43:25.773 364-1056/? E/AudioALSAPlaybackHandlerBase: openPcmDriver(), pcm_start(0xf10718a0) fail due to cannot start channel: Broken pipe
04-20 18:43:25.912 364-1056/? E/AudioALSAPlaybackHandlerBase: -getHardwareBufferInfo pcm_get_htimestamp fail, ret = -1, pcm_get_error = cannot start channel: Broken pipe
04-20 18:43:25.914 364-1056/? E/AudioALSAPlaybackHandlerBase: -getHardwareBufferInfo pcm_get_htimestamp fail, ret = -1, pcm_get_error = cannot start channel: Broken pipe
04-20 18:43:25.918 364-1056/? E/AudioFlinger: getNextBuffer, get null buffer
04-20 18:43:26.056 364-1041/? E/AudioPolicyManager: mapVoiceVoltoCustomVol 10447 Error : dMaxIndex = -1
04-20 18:43:26.193 1004-1073/? E/InputDispatcher: channel '1db7094 com.frank.ffmpeg/com.frank.ffmpeg.activity.AudioHandleActivity (server)' ~ Channel is unrecoverably broken and will be disposed!
04-20 18:43:26.193 1004-1073/? E/InputDispatcher: channel '218a3921 com.frank.ffmpeg/com.frank.ffmpeg.activity.MainActivity (server)' ~ Channel is unrecoverably broken and will be disposed!
04-20 18:43:26.266 1495-1649/? E/CellLocation: create GsmCellLocation
04-20 18:43:26.452 2603-2626/com.frank.ffmpeg E/GED: Failed to get GED Log Buf, err(0)
                                                     
                                                     [ 04-20 18:43:26.453  2603: 2626 I/         ]
                                                     elapse(include ctx switch):4601 (ms), eglInitialize
查了相关资料，可能是so平台兼容的原因，请问下，在你的demo里面，so怎么就放了一个，armeabi-v7a，谢谢

**Comment by xufuji456** [comment]
你好，请问是在哪个页面进行什么操作抛出的异常，是音频处理页面吗？其他操作有没报错呢？
我调试用魅蓝 note5

**Comment by 469065768** [comment]
音频拼接里面，一般引用libs应该是全平台的吧，因为你这里就引用了armeabi-v7a，是否应该添加其他cpu支持

**Comment by 469065768** [comment]
方便把你的其他cpu平台so文件邮件吗，469065768@qq.com，谢谢

**Comment by AlexTam930** [comment]
demo下载下来运行, 点击里面的所有功能都会应用闪退, 我觉得也是没有64位so库文件的原因导致. 楼主能在项目里更新下64位的ffmpeg编译so库文件吗? 谢谢.

**Comment by ZeroMCat** [comment]
你好，请问这个问题是什么导致呢，我也出现这个情况了。求解

**Comment by xufuji456** [comment]
你看下音频路径是否正确，读内存权限有没有

**Comment by zlongchao1755** [comment]
这个问题我也碰到过，我的情况是把命令中的“-threads”删掉就可以了。

**Comment by imyetse** [comment]
你好，armeabi的so文件有吗，arm64-v8a机型会崩溃呢，方便的话发我邮件 yeshieh@163.com

**Comment by xufuji456** [comment]
@469065768 @ZeroMCat @imyetse 已经添加arm64平台so库，请更新代码测试
