### ISSUE TITLE
图片合成视频不全

### ISSUE THREAD

**Issue by weilv1990** [xufuji456/FFmpegAndroid#31]
调用图片合成视频时，合成的视频只能看到前三张图片，第四张及以后的图片在视频中没有

**Comment by weilv1990** [comment]
图片合成视频使用工程里的方式：
"ffmpeg -f image2 -r 1 -i %simg#d.jpg -vcodec mpeg4 %s"
只能合成前面3到4张图片，后面的图片没有合成进去。
改成下面的合成命令：
 ffmpeg -f concat -safe 0 -i concat.txt output.mp4
是可以合成全部图片的
请问demo的实现方式是否有问题？

**Comment by xufuji456** [comment]
你的图片是不是按照img1.jpg、img2.jpg、img3.jpg、img4.jpg、img5.jpg这个依次命名呢

**Comment by weilv1990** [comment]
是按照这样的命名方式，是不是因为图片的尺寸长宽不同导致，但是用在pc端是可以用同样的命令合成的，只不过有warning

**Comment by weilv1990** [comment]
我用你的demo试最多只能合成4张图片

**Comment by xufuji456** [comment]
感谢你提出这个issue，经测试发现是不同图片分辨率与格式导致合成失败。
目前解决方案是先把图片分辨率转成一致，再合成视频。
