### ISSUE TITLE
导入live失败，删除了live包 然后报 A problem occurred configuring project ':app'.错误

### ISSUE THREAD

**Issue by 936492024** [xufuji456/FFmpegAndroid#32]
![image](https://user-images.githubusercontent.com/26289867/50259195-0fbc6880-043e-11e9-872a-798af0bb6822.png)
![image](https://user-images.githubusercontent.com/26289867/50259179-fd422f00-043d-11e9-940b-f04d80346b81.png)

**Comment by xufuji456** [comment]
Live是直播模块，你如果只用FFmpeg模块，可以把Live模块去掉，重新编译试下

**Comment by hongyang51** [comment]
@936492024 配置 NDK CMake  Najia 搞完就可以完全编译了

**Comment by CodeCaiSL** [comment]
嗯！同样是这种错误，配置 NDK CMake Najia 搞完就可以完全编译了是啥意思，楼上解决了吗

**Comment by hongyang51** [comment]
@Break369 先安装好 ndk 然后 安装cmake 再安装najia插件 这三个都安装之后 就会成功了 我已经成功的

**Comment by Break369** [comment]
najia插件主要是干啥用的

**Comment by Break369** [comment]
Najia插件是全名是Najia？为何找不到这个插件？

**Comment by CodeCaiSL** [comment]
Najia插件全面叫这个吗？为啥as搜索不到这个插件 @ @hongyang51

**Comment by hongyang51** [comment]
najia 我是 homebrew 安装的 是命令行命令 跟AS 无关啊... @Break369

**Comment by CodeCaiSL** [comment]
你用的是苹果来着吗 @hongyang51 没咋听明白你的意思

**Comment by hongyang51** [comment]
@Break369 就是这些工具都跟 as 无关  需要配置电脑环境变量   就跟 安装 java sdk 一样的流程 安装好所有工具

**Comment by tj297202234** [comment]
najia?娜迦？dota?什么鬼
