### ISSUE TITLE
如何集成到Android studio 中的问题

### ISSUE THREAD

**Issue by ChiuLui** [xufuji456/FFmpegAndroid#33]
请问一下大佬, 如何把你的Demo功能集成到项目中.
我Demo能运行起来也能使用功能.
我把你的so文件和cpp文件CMakeLists.txt都拷贝到了我的项目中. 可是一调命令就各种崩溃.
请问so文件要自己生成吗?还有什么要特别注意的地方吗?谢谢大佬.

**Comment by xufuji456** [comment]
1、你集成到项目里，可以拷贝so使用，也可以使用cpp源码；
2、so拷贝过去，FFmpegCmd.java文件需要放在com.frank.ffmpeg路径下；
     so不拷贝过去，直接使用cpp源码，把cpp中jni方法用的包名改成你项目的包名；
3、你看下音视频路径有没改成你手机对应的路径；
4、其他情况，需要看报错日志了；

**Comment by minne100** [comment]
我直接把so拷过去，把FFmpegCmd.java文件也放到com.frank.ffmpeg路径下，
第一次直接运行，提示找不到media-handle，之后我把它改成ffmpeg，又出现如下错误提示：
03-28 11:59:58.303: E/AndroidRuntime(14827): java.lang.UnsatisfiedLinkError: No implementation found for int com.frank.ffmpeg.FFmpegCmd.handle(java.lang.String[]) (tried Java_com_frank_ffmpeg_FFmpegCmd_handle and Java_com_frank_ffmpeg_FFmpegCmd_handle___3Ljava_lang_String_2)

**Comment by xufuji456** [comment]
jni的方法改为你自己工程的包名
