### ISSUE TITLE
音视频播放时间长了奔溃

### ISSUE THREAD

**Issue by libw1** [xufuji456/FFmpegAndroid#34]
01-08 12:17:10.421 6479-6869/com.frank.ffmpeg E/Surface: Surface::unlockAndPost failed, no locked buffer
01-08 12:17:10.424 6479-6889/com.frank.ffmpeg I/MediaPlayer: decode audio stream = 2927
01-08 12:17:10.426 6479-6888/com.frank.ffmpeg I/MediaPlayer: decode video stream = 1629
01-08 12:17:10.448 6479-6889/com.frank.ffmpeg I/MediaPlayer: decode audio stream = 2928
01-08 12:17:10.468 6479-6888/com.frank.ffmpeg I/MediaPlayer: decode video stream = 1630
01-08 12:17:10.470 297-1399/? E/BufferQueueProducer: [SurfaceView - com.frank.ffmpeg/com.frank.ffmpeg.activity.VideoPlayerActivity] dequeueBuffer: BufferQueue has been abandoned
01-08 12:17:10.470 6479-6869/com.frank.ffmpeg E/Surface: dequeueBuffer failed (No such device)
01-08 12:17:10.472 6479-6889/com.frank.ffmpeg I/MediaPlayer: decode audio stream = 2929
01-08 12:17:10.481 6479-6869/com.frank.ffmpeg E/Surface: Surface::unlockAndPost failed, no locked buffer
01-08 12:17:10.496 6479-6889/com.frank.ffmpeg I/MediaPlayer: decode audio stream = 2930
01-08 12:17:10.509 6479-6888/com.frank.ffmpeg A/libc: Fatal signal 11 (SIGSEGV), code 1, fault addr 0x38 in tid 6888 (Thread-3)

**Comment by xufuji456** [comment]
这个后续优化下
