### ISSUE TITLE
Android studio 不知道如何运行

### ISSUE THREAD

**Issue by z8806c** [xufuji456/FFmpegAndroid#35]
Android studio 不知道如何运行

**Comment by xufuji456** [comment]
你用Android Studio导入项目就可以了
音视频路径需要改成你手机对应的路径

**Comment by hongyang51** [comment]
@z8806c  配置 NDK CMake  Najia 搞完就可以完全编译了

**Comment by minne100** [comment]
编译后并没有生成media-handle啊

**Comment by xufuji456** [comment]
media-handle在build/intermediates/cmake里面
<img width="257" alt="image" src="https://user-images.githubusercontent.com/20047648/68024336-c89d3600-fce4-11e9-8671-5e989af39061.png">
