### ISSUE TITLE
音频剪切后 0kb

### ISSUE THREAD

**Issue by lxb89** [xufuji456/FFmpegAndroid#37]
音频裁剪后生成了cut.mp3文件，但是文件大小为0，不能播放，求作者指教

**Comment by xufuji456** [comment]
原始音频是什么格式的呢
另外，原音频时长多少，你剪切多少

**Comment by DaveBoy** [comment]
我也遇到了，原始音频是MP3  3:38   用的demo的剪切   直接放了一首歌到根目录命名为tiger.mp3

**Comment by DaveBoy** [comment]
> 音频裁剪后生成了cut.mp3文件，但是文件大小为0，不能播放，求作者指教

改一下命令就行了  看我的另一个issues
-i 124.mp3 -vn -acodec copy -ss 00:00:00 -t 00:01:32 output.mp3  类似这种

**Comment by xufuji456** [comment]
@lxb89 音频剪切问题修复了，请更新最新git代码
