### ISSUE TITLE
添加水印后视频模糊问题

### ISSUE THREAD

**Issue by hulk910** [xufuji456/FFmpegAndroid#41]
大神你好，使用demo添加水印后得到的视频被压缩了，这是为什么呢？是不是被转码了？有解决方法么？

**Comment by alian69359184** [comment]
”ffmpeg -i input.MP4  make.png -b:v 1500K output.mp4”在输入视频字段前调整码率

**Comment by alian69359184** [comment]
"ffmpeg -i input.mp4 -i make.png -filter_complex overlay=0:0 -b:v 1500k output.mp4"

**Comment by xufuji456** [comment]
@hzj926 你好，视频水印命令增加了分辨率、码率参数，分辨率和码率设置越高，得到视频质量越好
