### ISSUE TITLE
视频添加水印

### ISSUE THREAD

**Issue by youtiandroid** [xufuji456/FFmpegAndroid#42]
使用框架添加水印   输出的视频编码为mpeg4 的     问：要怎样配置才可以输出h264编码格式的？

**Comment by xufuji456** [comment]
你把输出文件后缀改成.h264，应该就可以了

**Comment by youtiandroid** [comment]
是在哪个类？可以附上简单的代码？

**Comment by xufuji456** [comment]
ffmpeg -i %s -i %s -s %s -b:v %s -vcodec h264 -filter_complex overlay=0:0 %s
@youtiandroid 主要是使用-vcodec h264指定编码格式
