### ISSUE TITLE
向大神请教个问题，我运行demo的时候，点大部分功能都会直接闪退

### ISSUE THREAD

**Issue by bigbobi** [xufuji456/FFmpegAndroid#43]
比如，我点画面拼接，但是会报
 java.lang.UnsatisfiedLinkError: No implementation found for int com.frank.ffmpeg.FFmpegCmd.Java_com_frank_ffmpeg_FFmpegCmd_test(java.lang.String[]) (tried Java_com_frank_ffmpeg_FFmpegCmd_Java_1com_1frank_1ffmpeg_1FFmpegCmd_1test and Java_com_frank_ffmpeg_FFmpegCmd_Java_1com_1frank_1ffmpeg_1FFmpegCmd_1test___3Ljava_lang_String_2)
        at com.frank.ffmpeg.FFmpegCmd.Java_com_frank_ffmpeg_FFmpegCmd_test(Native Method)
        at com.frank.ffmpeg.FFmpegCmd.access$000(FFmpegCmd.java:3)
        at com.frank.ffmpeg.FFmpegCmd$1.run(FFmpegCmd.java:27)
        at java.lang.Thread.run(Thread.java:776)

这个错误想请教下这个错误如何解决？

**Comment by xufuji456** [comment]
没有这个方法的实现：Java_com_frank_ffmpeg_FFmpegCmd_test
test这个方法是不是你加上去的呢，需要在jni加上对应方法
另外，点击音频/视频处理按钮，需要指定你手机对应的音视频路径

**Comment by bigbobi** [comment]
@xufuji456 但是我已经在ffmpeg_cmd这个文件里添加Java_com_frank_ffmpeg_FFmpegCmd_test这个方法了，而且这个方法就是本来你写在项目中的那个handler方法改个名字，而且关于音视频路径我也替换成我对应的路径了，但还是报这个错

**Comment by xufuji456** [comment]
java和cpp代码你有没对应修改呢
java有个FFmpegCmd.java 和 cpp有个ffmpeg_cmd.c需要一起改的
