### ISSUE TITLE
实时推流，出现花屏

### ISSUE THREAD

**Issue by xwlichen** [xufuji456/FFmpegAndroid#47]
实时推流，播放时出现花屏，绿色的蒙版一样，还有音频编码失败，这些问题一般是什么原因引起的，在阿里云上推流没问题

**Comment by xufuji456** [comment]
1、如果是偶尔出现绿屏，是丢包、解码出错导致的
2、如果是一直绿屏，可能是编码格式有问题，也可能是硬解码出问题

**Comment by xwlichen** [comment]
好的，谢谢，我这还有个问题，对于推流，如果推流地址被占用了会崩溃，这种的崩溃异常该怎么捕获呢，能给个思路吗，万分感谢

**Comment by xwlichen** [comment]
是rtmp.a的静态库问题，在报连接的问题的时候会rtmp.c 的WriteN 会陷入死循环，需要自己导入rtmpdump源码进行修改
