### ISSUE TITLE
大神，你好。 pcm转wav好像不能成功。 会崩溃，请问您遇到过吗

### ISSUE THREAD

**Issue by XingHaoxiang** [xufuji456/FFmpegAndroid#5]
05-07 16:57:30.922 9474-9552/? A/libc: Fatal signal 11 (SIGSEGV), code 1, fault addr 0x10 in tid 9552 (Thread-3)
                                       
                                       [ 05-07 16:57:30.922   415:  415 W/         ]
                                       debuggerd: handling request: pid=9474 uid=10338 gid=10338 tid=9552
05-07 16:57:30.932 1325-3063/? E/Process: isHighLoadProcess: get cpu failed
05-07 16:57:31.002 9563-9563/? A/DEBUG: *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
05-07 16:57:31.002 9563-9563/? A/DEBUG: Build fingerprint: 'HUAWEI/NXT-AL10/HWNXT:7.0/HUAWEINXT-AL10/C00B596:user/release-keys'
05-07 16:57:31.002 9563-9563/? A/DEBUG: Revision: '0'
05-07 16:57:31.003 9563-9563/? A/DEBUG: ABI: 'arm'
05-07 16:57:31.003 9563-9563/? A/DEBUG: pid: 9474, tid: 9552, name: Thread-3  >>> com.frank.ffmpeg <<<
05-07 16:57:31.003 9563-9563/? A/DEBUG: signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x10
05-07 16:57:31.003 9563-9563/? A/DEBUG:     r0 00000000  r1 00000001  r2 00000000  r3 ffffffff
05-07 16:57:31.003 9563-9563/? A/DEBUG:     r4 e480d864  r5 c797f1a8  r6 c797ef50  r7 c797ebd0
05-07 16:57:31.003 9563-9563/? A/DEBUG:     r8 c797ef50  r9 c7a8ed00  sl 00000000  fp c797eedc
05-07 16:57:31.003 9563-9563/? A/DEBUG:     ip d6cf191c  sp c797e4e0  lr d6cc9c53  pc d6cc9e68  cpsr 800f0030
05-07 16:57:31.005 9563-9563/? A/DEBUG: backtrace:
05-07 16:57:31.005 9563-9563/? A/DEBUG:     #00 pc 00010e68  /data/app/com.frank.ffmpeg-1/lib/arm/libmedia-handle.so
05-07 16:57:31.005 9563-9563/? A/DEBUG:     #01 pc 0000f975  /data/app/com.frank.ffmpeg-1/lib/arm/libmedia-handle.so
05-07 16:57:31.005 9563-9563/? A/DEBUG:     #02 pc 0000f187  /data/app/com.frank.ffmpeg-1/lib/arm/libmedia-handle.so (run+318)
05-07 16:57:31.005 9563-9563/? A/DEBUG:     #03 pc 0002904f  /data/app/com.frank.ffmpeg-1/lib/arm/libmedia-handle.so (Java_com_frank_ffmpeg_FFmpegCmd_handle+194)
05-07 16:57:31.005 9563-9563/? A/DEBUG:     #04 pc 003788b9  /data/app/com.frank.ffmpeg-1/oat/arm/base.odex (offset 0x35c000)
05-07 16:57:31.387 633-921/? E/logserver: imonitor_add_dynamic_path, path:/data/system/dropbox/SYSTEM_TOMBSTONE@1525683451303.txt.gz
05-07 16:57:31.393 1325-3060/? E/HsmCoreServiceImpl: onTransact in code is: 102
05-07 16:57:31.416 9575-9575/? E/SchedPolicy: open of dev/cpuctl/limit_fg/tasks failed: Permission denied
05-07 16:57:31.417 9575-9575/? E/SchedPolicy: open of dev/cpuctl/bg_non_interactive/limit_bg/tasks failed: Permission denied
05-07 16:57:31.453 1325-1962/? E/Process: isHighLoadProcess: get cpu failed
05-07 16:57:31.465 440-1568/? E/ion: set flags ioctrl failed!
05-07 16:57:31.651 440-451/? E/ion: set flags ioctrl failed!
05-07 16:57:31.654 440-451/? E/ion: set flags ioctrl failed!
05-07 16:57:31.656 440-451/? E/ion: set flags ioctrl failed!

我不知道这log有没有用 ，Mate8手机

**Comment by XingHaoxiang** [comment]
05-07 17:03:33.933 30170-30295/? A/libc: Fatal signal 11 (SIGSEGV), code 1, fault addr 0x10 in tid 30295 (Thread-5)
05-07 17:03:33.984 30307-30307/? A/DEBUG: *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
05-07 17:03:33.984 30307-30307/? A/DEBUG: Build fingerprint: 'HUAWEI/ALP-AL00/HWALP:8.0.0/HUAWEIALP-AL00/125(SP3C00):user/release-keys'
05-07 17:03:33.984 30307-30307/? A/DEBUG: Revision: '0'
05-07 17:03:33.984 30307-30307/? A/DEBUG: ABI: 'arm'
05-07 17:03:33.984 30307-30307/? A/DEBUG: pid: 30170, tid: 30295, name: Thread-5  >>> com.frank.ffmpeg <<<
05-07 17:03:33.984 30307-30307/? A/DEBUG: signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x10
05-07 17:03:33.984 30307-30307/? A/DEBUG: Cause: null pointer dereference
05-07 17:03:33.984 30307-30307/? A/DEBUG:     r0 00000000  r1 00000001  r2 00000000  r3 f45354f7
05-07 17:03:33.984 30307-30307/? A/DEBUG:     r4 f28efba4  r5 00000001  r6 00000000  r7 cf541bf0
05-07 17:03:33.984 30307-30307/? A/DEBUG:     r8 0000004b  r9 d04e3400  sl 00000000  fp cf541f04
05-07 17:03:33.984 30307-30307/? A/DEBUG:     ip cf57b91c  sp cf541500  lr cf553c53  pc cf553e68  cpsr 800f0030
05-07 17:03:33.985 30307-30307/? A/DEBUG: backtrace:
05-07 17:03:33.985 30307-30307/? A/DEBUG:     #00 pc 00010e68  /data/app/com.frank.ffmpeg-dJ9FP06MAI2aa1q6iwG_9g==/lib/arm/libmedia-handle.so
05-07 17:03:33.985 30307-30307/? A/DEBUG:     #01 pc 0000f975  /data/app/com.frank.ffmpeg-dJ9FP06MAI2aa1q6iwG_9g==/lib/arm/libmedia-handle.so
05-07 17:03:33.985 30307-30307/? A/DEBUG:     #02 pc 0000f187  /data/app/com.frank.ffmpeg-dJ9FP06MAI2aa1q6iwG_9g==/lib/arm/libmedia-handle.so (run+318)
05-07 17:03:33.985 30307-30307/? A/DEBUG:     #03 pc 0002904f  /data/app/com.frank.ffmpeg-dJ9FP06MAI2aa1q6iwG_9g==/lib/arm/libmedia-handle.so (Java_com_frank_ffmpeg_FFmpegCmd_handle+194)
05-07 17:03:33.985 30307-30307/? A/DEBUG:     #04 pc 0000a269  /data/app/com.frank.ffmpeg-dJ9FP06MAI2aa1q6iwG_9g==/oat/arm/base.odex (offset 0xa000)
05-07 17:03:34.620 672-672/? E//system/bin/tombstoned: Tombstone written to: /data/tombstones//tombstone_02
                                                       
                                                       --------- beginning of system
05-07 17:03:34.692 1185-1399/? E/InputDispatcher: channel 'f3f1662 com.frank.ffmpeg/com.frank.ffmpeg.activity.AudioHandleActivity (server)' ~ Channel is unrecoverably broken and will be disposed!
05-07 17:03:34.696 1185-1399/? E/InputDispatcher: channel '3bb3438 com.frank.ffmpeg/com.frank.ffmpeg.activity.MainActivity (server)' ~ Channel is unrecoverably broken and will be disposed!

mate10手机的log

**Comment by xufuji456** [comment]
你好，pcm转wav属于编码，原来提供的是转码接口（不好意思）。
刚才提交了音频编码接口（在音频处理页面最下面），你更新代码试下。。

**Comment by XingHaoxiang** [comment]
转换完成了，但是转换出来的音频效果不好，好像是怪物史瑞克的声音

**Comment by xufuji456** [comment]
可能与采样率、声道有关。
你的pcm音频采样率多少，channel是单声道还是立体声道。
我昨天匆匆在代码写固定采样率8000hz、单声道，你可以根据实际情况修改看看。

**Comment by XingHaoxiang** [comment]
感谢大神回复，我是百度语音生成的pcm 应该是16K 双声道吧、 我不太懂这个。 我大概看看吧， 谢谢您

**Comment by xufuji456** [comment]
不客气，我在audio目录下上传一段pcm数据：8K、单声道的。你可以用它来编码成wav对比效果。
我今晚再把采样率、声道改为入参传进去，这样灵活点。

**Comment by XingHaoxiang** [comment]
我可以给您一个测试的pcm。 

现在的功能是否支持多个pcm文件进行拼接？

**Comment by xufuji456** [comment]
应该支持的，你试下音频拼接那个方法，先试下两个pcm拼接（多个文件后续可扩展）
我以前拼接两个MP3是可以的
另外，可以用Audacity工具查看pcm文件参数、播放pcm裸流

**Comment by XingHaoxiang** [comment]
我试过拼接pcm 不行，会崩溃。 拼接wav拼接不成功，两段wav拼接的话，合并结果会返回第一个音频文件。第二个好像没有合并进去。 这是我测试完后的结果。。  :1st_place_medal:

**Comment by xufuji456** [comment]
1、原来的音频合并只MP3、AAC、AMR等格式，不支持PCM裸流、WAV。
2、刚才我更新了代码，单独做PCM裸流文件的合并，你拉代码试下。
3、至于WAV，它比较特殊，是44字节+PCM裸流数据。你可以试下间接合并：
把两个WAV文件的PCM数据先后拷贝到新文件，得到合并后的PCM，然后把PCM文件编码成WAV。
**另外，建议你先了解WAV音频格式，他与PCM的关系。**

**Comment by xufuji456** [comment]
1、原来的音频合并只支持MP3、AAC、AMR等格式，不支持PCM裸流、WAV。
2、刚才我更新了代码，单独做PCM裸流文件的合并，你拉代码试下。
3、至于WAV，它比较特殊，是44字节+PCM裸流数据。你可以试下间接合并：
把两个WAV文件的PCM数据先后拷贝到新文件，得到合并后的PCM，然后把PCM文件编码成WAV。
**另外，建议你先了解WAV音频格式，他与PCM的关系。**

**Comment by XingHaoxiang** [comment]
感谢大神， 看到消息晚了， 我已经拉最新代码了。 :smile:  现在往我的项目里合并代码呢， 集成还有些问题需要我改， 不过还是谢大神的帮忙了 :+1:

**Comment by Dhy521** [comment]
请问你解决了吗  我也是用的百度长语音功能  出来的pcm文件 但是我想转MP3  和你情况一样么
