### ISSUE TITLE
实现视频添加水印

### ISSUE THREAD

**Issue by caiguangyi** [xufuji456/FFmpegAndroid#55]
<img width="954" alt="WechatIMG4" src="https://user-images.githubusercontent.com/19151532/58792881-9e592680-8627-11e9-8349-3f70b5e4db83.png">

大神，我将项目摘取了主要代码，在另一个项目上使用，就出现上图的那个错误，显示找不到那个handle方法，这是为什么啊？

**Comment by xufuji456** [comment]
你有没把cpp目录的代码复制过去，另外cpp的jni方法的包名改为你自己工程的包名

**Comment by pkxutao** [comment]
"另外cpp的jni方法的包名改为你自己工程的包名",
你好，第一次搞jni方法，请问这句话具体怎么操作？找了好多地方也没理解

**Comment by xufuji456** [comment]
@pkxutao 这是调用jni方法的动态注册方式，需要完整包名+类名+方法名的。
jni方法需要用到包名，移植到其他工程，所以需要更换jni方法的包名
