### ISSUE TITLE
点击实时推流直播，log显示音频编码失败，但是可以听见声音，不能看见视频是什么原因

### ISSUE THREAD

**Issue by SunnyLuna** [xufuji456/FFmpegAndroid#56]
![图片](https://user-images.githubusercontent.com/21188380/59407274-57b3bb00-8de3-11e9-94c1-4e5602f39c3e.png)

**Comment by xufuji456** [comment]
是手机端看不到视频，还是服务端看不到视频画面。
检查下视频初始化参数，可能是设置分辨率、码率参数问题

**Comment by xufuji456** [comment]
和issue50重复：https://github.com/xufuji456/FFmpegAndroid/issues/50
