### ISSUE TITLE
ts格式转mp4格式只能转出一帧

### ISSUE THREAD

**Issue by GhRyuJin** [xufuji456/FFmpegAndroid#59]
ts格式转mp4格式只能转出一帧，如果去掉音频就没有问题

**Comment by xufuji456** [comment]
你的音频是什么编码，是不是mp3

**Comment by xufuji456** [comment]
转码采用acodec copy 形式，能不能播放取决于原音视频编码。
或者转码时，根据实际需求，指定音视频编码，比如 acodec aac vcodec h264
