### ISSUE TITLE
pcm转mp3

### ISSUE THREAD

**Issue by Dhy521** [xufuji456/FFmpegAndroid#61]
请问大佬  用音频转码 pcm格式转MP3 出来的大小是0B 请问这是什么情况
我看到有个帖子你留言说 用音频编码 但是你说要激活MP3库 这个库怎么激活

**Comment by xufuji456** [comment]
需要重新编译ffmpeg，把libmp3lame编译进去

**Comment by xufuji456** [comment]
我加入了libmp3lame的mp3库，现在支持mp3转码了，请用最新版本的Mp3Convertor类进行转码
