### ISSUE TITLE
剪切之后大小为0kb的解决方法

### ISSUE THREAD

**Issue by DaveBoy** [xufuji456/FFmpegAndroid#63]
String cutAudioCmd = "ffmpeg -i %s -vn -acodec copy -ss %s -t %s %s";
        cutAudioCmd = String.format(cutAudioCmd, srcFile, "00:00:"+startTime, "00:00:"+duration, targetFile);

正常命令形式  “ffmpeg -i 124.mp3 -vn -acodec copy -ss 00:00:00 -t 00:01:32 output.mp3“

**Comment by xufuji456** [comment]
建议不错
