### ISSUE TITLE
关于合并音频之后第二段自动跳过的问题解决方案

### ISSUE THREAD

**Issue by DaveBoy** [xufuji456/FFmpegAndroid#64]
1.创建一个文件mylist.txt，包含你想要连接的所有文件，格式如下：
file 'path/to/file1'
file 'path/to/file2'
file 'path/to/file3'

2.ffmpeg命令
ffmpeg -f concat -safe 0 -i mylist.txt -c copy output

经测试，ok

**Comment by DaveBoy** [comment]
同一个音频合并是ok的  但是有些音频合并还是不行   估计是音频具体的编码啥的不一样

**Comment by DaveBoy** [comment]
最终解决方案：https://blog.csdn.net/tian2342/article/details/99303883

**Comment by xufuji456** [comment]
谢谢你指出的方案

**Comment by xufuji456** [comment]
为了统一合并音频后编码参数，采用重新编码方式：
ffmpeg -i concat:%s|%s -acodec libmp3lame -ab 128k -ac 2 -ar 44100 concat.mp3
