### ISSUE TITLE
请问大神，ffmpeg不可以多线程吗，我用-threads 4为什么无效呢

### ISSUE THREAD

**Issue by bsmmaoshenbo** [xufuji456/FFmpegAndroid#65]
请问大神，ffmpeg不可以多线程吗，我用-threads 4为什么无效呢

**Comment by xufuji456** [comment]
你是在哪里设置-threads 4

**Comment by trycatchx** [comment]
好像不支持 多线程，请问这个要怎么处理？

**Comment by xufuji456** [comment]
要是转码应该不支持多线程，可以设置preset:v super-fast来提升转码速度。
另外，根据视频码率、分辨率而定，设定的码率、分辨率越小，转码速度越快
