### ISSUE TITLE
音频剪切失败

### ISSUE THREAD

**Issue by yusheng-jia** [xufuji456/FFmpegAndroid#7]
剪切音频失败了，你有联系方式吗？方便有问题联系下

**Comment by xufuji456** [comment]
你的音频是什么格式的。除了音频剪切，其他的功能正常吗

**Comment by yusheng-jia** [comment]
音频是mp3格式的，我看了你命令，ffmpeg -i %s -ss %d -t %d  %s 我加了 ffmpeg -i %s -ss %d -t %d -acodec copy %s 就可以了，不知道啥原因呢？另外 我自己写了一个命令：ffmpeg -i cm20180503020.mp3 -af "volume=0.4" increateVol.mp3 在PC上可以执行成功，在Android端死活不成功呢。

**Comment by yusheng-jia** [comment]
有QQ吗？可以具体探讨下哈，谢谢了

**Comment by xufuji456** [comment]
我QQ是839789740
