### ISSUE TITLE
手机竖屏录制的视频，转码后旋转了90°

### ISSUE THREAD

**Issue by mako-o-o** [xufuji456/FFmpegAndroid#76]
您好，手机录制的视频，mp4（本地播放为竖屏）转flv格式后，逆时针旋转了90度，该在哪里加上rotate参数呢？

**Comment by xufuji456** [comment]
感谢你提这个问题，如果要用到libx264库请更新代码
转码时，指定视频编码器可以解决旋转问题：ffmpeg -i %s -vcodec mpeg4 -acodec copy %
或者ffmpeg -i %s -vcodec libx264 -acodec copy %
