### ISSUE TITLE
Emulator: Trying to erase a non-existent color buffer with handle 0

### ISSUE THREAD

**Issue by leon524** [xufuji456/FFmpegAndroid#77]
请问这是什么问题导致的

**Comment by xufuji456** [comment]
你是进行什么操作报的异常

**Comment by leon524** [comment]
播放视频，和视频反向播放，选择视频文件确定后闪退到菜单栏



发自我的iPhone


------------------ Original ------------------

**Comment by xufuji456** [comment]
请发下具体点的错误日志；
顺便问下，其他功能有没问题

**Comment by xufuji456** [comment]
如果是arm64平台原因，请更改最新代码测试，已支持arm64
