### ISSUE TITLE
视频画中画时, 前面的视频没有缩放 

### ISSUE THREAD

**Issue by Minuit-Z** [xufuji456/FFmpegAndroid#78]
这边好像是直接overlay上面了, 想加上等比例缩放但是报错:  
把命令改成如下 , 会直接报错
ffmpeg -i %s -i %s -filter_complex [1]scale=iw/2:ih/2[pip];[0][pip]overlay=main_w-overlay_w-10:main_h-overlay_h-10 %s

**Comment by xufuji456** [comment]
有什么报错信息
