### ISSUE TITLE
请问大神这个怎么集成到eclipse呀

### ISSUE THREAD

**Issue by KnowledgeBeggar** [xufuji456/FFmpegAndroid#8]

**Comment by xufuji456** [comment]
你先创建一个工程，把Java和c源代码拷过去。另外，eclipse是使用Android.mk文件的，你需要根据原来的CmakeLists.txt，改成Android.mk文件，再加上application.mk文件。

**Comment by KnowledgeBeggar** [comment]
我准备在AS上直接生成so文件，然后再把java代码复制过去，这样可以么。
ffmpeg的其它架构的so文件能麻烦你发给我么，十分感谢。
975904364@qq.com
