### ISSUE TITLE
ffmpeg 源码优化 rtsp延时

### ISSUE THREAD

**Issue by tommyfeng** [xufuji456/FFmpegAndroid#81]
大神，能给我一下您优化 rtsp延时的 ffmpeg 源码吗? 我按照您在CSDN 上的博客一步一步进行修改的，但是没有作用，且播放rtsp 几秒画面就卡住不动了，希望您看到可以回复一下，万分感谢！！！

**Comment by linglingdasan** [comment]
你好，请问你是怎么测试的rtsp方案呢，我看大牛的项目里面只有一个ijkplay的播放项目，没有手机端或者pc端的rtsp推流 部分呢，请大牛 赐教

**Comment by tommyfeng** [comment]
推流部分我这里已经是有了的，我只需要播放。 如果你没有自己搭建的rtsp 服务器的话，你可以直接用PC的 VLC客户端开推流服务

**Comment by linglingdasan** [comment]
嗯，谢谢大牛，多谢

**Comment by iopa788** [comment]
@tommyfeng  你好！你的推流的demo能给我一份嘛
