### ISSUE TITLE
根据你博客改法，rtsp的延迟是减小了一些，而用你的FFmpegAndroid这个工程的so库，延迟会很小

### ISSUE THREAD

**Issue by Dreamskya** [xufuji456/FFmpegAndroid#82]
您好，博主，请教下，你这个FFmpegAndroid工程对rtsp，优化了哪些地方呢？根据你博客改法，是可以减少一些延迟，但还是存在180-300ms，我自己的项目，只换了你这个工程的so，延迟是在130ms，你这个效果会更好。请教下，是还要改什么地方吗？
需要换FFmpeg版本的吗？还是你对FFmpeg里面的代码做了优化呢？

**Comment by linglingdasan** [comment]
你好，请问你是怎么测试的rtsp方案呢，我看大牛的项目里面只有一个ijkplay的播放项目，没有手机端或者pc端的rtsp推流  部分呢，请大牛 赐教

**Comment by Dreamskya** [comment]
用自己的相机设备推流的，博主这个只是拉流用的。

**Comment by linglingdasan** [comment]
谢谢大神，多谢

**Comment by Mokyyds** [comment]
复议，大佬应该是对IjkPlayer做了rtsp的深度优化，如果方便的话还是希望能把优化后的ijkPlayer源码发一下，想在底层做录制和截图的功能。
