### ISSUE TITLE
项目运行直接提示unknown，界面漆黑一片

### ISSUE THREAD

**Issue by passionfun** [xufuji456/FFmpegAndroid#83]
项目运行直接提示unknown，界面漆黑一片

**Comment by linglingdasan** [comment]
我也碰到这个问题了，是运行onlive这个项目吧，请问楼主解决了吗？

**Comment by zijin2014** [comment]
运行app起不来，运行onlive  提示unknown，界面漆黑一片，我是换as版本解决的

**Comment by xufuji456** [comment]
@passionfun @linglingdasan 我更换了可用直播地址，你们更新代码试下OnLive模块
