### ISSUE TITLE
图片转视频无法使用

### ISSUE THREAD

**Issue by iotxc** [xufuji456/FFmpegAndroid#84]
如题

**Comment by xufuji456** [comment]
你有没把图片放在同一文件夹里，并且统一命名为img1、img2、img3这样呢

**Comment by iotxc** [comment]
我在img文件夹中放了三张图img/img1.jpg, img2.jpg, img3.jpg, 但是点击“图片合成视频”按钮，打开的界面只能选择文件，不能选择文件夹。而且在选择回调处理那里你还判断了选择的文件不是视频就不处理
 if (!FileUtil.isVideo(srcFile)) {
            showToast(getString(R.string.wrong_video_format));
            return;
}

**Comment by xufuji456** [comment]
是我考虑不够周到，图片合成视频不应该判断是不是视频。
你可以在修改代码试下

**Comment by xufuji456** [comment]
我处理了图片合成视频的情况，指定img目录，不跳到文件管理器选择文件。
目前是可以合成视频的，请更新最新版本试下。
建议放多几张图片，如果图片比较少，建议把帧率frameRate设为1

**Comment by iotxc** [comment]
博主辛苦了，我之前尝试过修改你的代码但是没成功，现在来看应该是命令的问题。
我刚刚又更新你的代码测试了下，可以合成视频，但是最多只能合成四张是什么问题？

**Comment by xufuji456** [comment]
有两点要确认：
1、你在img目录放多少张图片，图片是不是按照img1.jpg、img2.jpg、img3.jpg、img4.jpg、img5.jpg、img6.jpg这样递增命名的；
2、你有没修改帧率frameRate，假如帧率frameRate=2，代表1s合成2张图片，那么8张图片合成的视频为4s；

**Comment by iotxc** [comment]
我img文件夹放了8张图片，稍微有点大，每张大约400~500k的样子，命名都是按照统一格式命名的，使用的frameRate为1.从日志的结果来看并没有遍历完文件夹下所有的图片
![TIM截图20191212160702](https://user-images.githubusercontent.com/23256376/70694156-e1443700-1cf9-11ea-85f5-175281138bfe.png)
![TIM截图20191212160740](https://user-images.githubusercontent.com/23256376/70694162-e5705480-1cf9-11ea-9168-bb0282319072.png)

**Comment by xufuji456** [comment]
我试了18张图片的情况：
设置frameRate=1，合成视频是18s；
设置frameRate=2，合成视频是9s；
设置frameRate=3，合成视频是6s；
你换一些图片或者放多几张图片试下，最好所有图片尺寸大小一致(可以用视频批量抽取图片)

**Comment by iotxc** [comment]
谢谢， 我更换了一些图片，但还是有些小问题，我再研究下
