### ISSUE TITLE
问题咨询

### ISSUE THREAD

**Issue by YuLingRui** [xufuji456/FFmpegAndroid#86]
大神你好。 我把你的cpp/ffmpeg 的这些文件copy到我的工程中。cmakelist中也配置完毕。 但是编译的时候出现问题

![B1RNMTJPDX5XJUE@(RTG45X](https://user-images.githubusercontent.com/12409566/70294029-1eea2100-181d-11ea-85ed-74f623926072.png)
希望大神麻烦指点一下。 谢谢了

**Comment by xufuji456** [comment]
重复引用了

**Comment by YuLingRui** [comment]
谢谢，找到原因了。

**Comment by xufuji456** [comment]
@YuLingRui 不用客气
