### ISSUE TITLE
问题咨询

### ISSUE THREAD

**Issue by YuLingRui** [xufuji456/FFmpegAndroid#87]
![P(1$}5}~0LF8 J_) 5B) 7O](https://user-images.githubusercontent.com/12409566/70412718-6f1ce980-1a90-11ea-8c81-c5ad27c578aa.png)
我用您的代码尝试把两个mp3合并 但是并没有生成concat.mp3 但是concat播放失败， 只播放了不到10秒， 没有把这两个MP3完整的播放

**Comment by xufuji456** [comment]
原本两段mp3音频时长是多少呢

**Comment by YuLingRui** [comment]
都是3分多钟 不到4分钟

**Comment by xufuji456** [comment]
你好，合并音频的问题以解决，合并后转码为统一mp3格式，请更新代码验证下
