### ISSUE TITLE
合并视频

### ISSUE THREAD

**Issue by LuckyJayce** [xufuji456/FFmpegAndroid#88]
请问可以用这个执行 
ffmpeg -f concat -i filelist.txt -c copy output.mkv  命令么

现在执行报
signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x2c
Cause: null pointer dereference

**Comment by xufuji456** [comment]
-c copy应该是不行的，可以用-vcodec copy -acodec copy试下。
另外，filelist.txt需要是绝对路径，否则FFmpeg没法打开它。
