### ISSUE TITLE
硬解开启黑屏问题

### ISSUE THREAD

**Issue by Dreamskya** [xufuji456/FFmpegAndroid#89]
博主，硬解开启，会黑屏现象，你有遇到过吗？或者，怎么样才能开启硬解呢？

**Comment by xufuji456** [comment]
要解码的视频是什么格式的、视频分辨率多少。
硬解取决于手机解码芯片能力：支持格式有限，而且一般支持分辨率在1080P左右，高端手机可以2K

**Comment by Dreamskya** [comment]
网上看了资料，解决了，ijkmedia/ijkplayer/android/pipeline/ffpipenode_android_mediacodec_vdec.c#249
recreate_format_l  添加了这个// Codec specific data
  SDL_AMediaFormat_setBuffer(opaque->input_aformat, "csd-0", opaque->codecpar->extradata, opaque->codecpar->extradata_size);
  ALOGE("csd-0: naked\n");
是可以开启硬解，但是延迟好大，比软解延迟严重多了，至少延迟3秒，而且很卡顿。不知道为何。
编码是H264的，720P 30fps

**Comment by Dreamskya** [comment]
@xufuji456 博主，您好，请教下，按照你深度优化rtsp直播方法，用软解进行预览，延迟是在200ms内，但开启硬解延迟500ms，硬解能不能也优化到和软解一样保持200ms?你有什么建议吗？

**Comment by xufuji456** [comment]
硬解mediacodec内部会缓存好几帧，所以延时比较大。
目前我没有找到很好的方案解决硬解延时。
理论上，视频帧率越大，解码延时越小，前提是解码能力跟得上。

**Comment by Dreamskya** [comment]
嗯嗯，了解，谢谢博主回复，测试过1080P，高通手机硬解还不如低端手机硬解，低端延迟400ms左右，高通手机硬解延迟2秒，不知道为何？
