### ISSUE TITLE
.mov剪切,只能保存到一帧，如果设置-acodec copy -an 就可以裁剪到对应的时间视频，-acodec我设置其他的就会闪退，大神这个能抢救一下吗

### ISSUE THREAD

**Issue by zijin2014** [xufuji456/FFmpegAndroid#91]
General
Complete name                  : C:\Users\Administrator\Desktop\FILE191211-093257-004504F.MOV
Format                         : MPEG-4
Format profile                 : QuickTime
Codec ID                       : qt   0000.02 (qt  )
File size                      : 73.3 MiB
Duration                       : 1 min 0 s
Overall bit rate               : 10.2 Mb/s

Video
ID                             : 1
Format                         : AVC
Format/Info                    : Advanced Video Codec
Format profile                 : Main@L4
Format settings                : CABAC / 1 Ref Frames
Format settings, CABAC         : Yes
Format settings, ReFrames      : 1 frame
Codec ID                       : avc1
Codec ID/Info                  : Advanced Video Coding
Duration                       : 1 min 0 s
Bit rate                       : 9 918 kb/s
Width                          : 1 920 pixels
Height                         : 1 080 pixels
Display aspect ratio           : 16:9
Frame rate mode                : Constant
Frame rate                     : 29.970 (30000/1001) FPS
Color space                    : YUV
Chroma subsampling             : 4:2:0
Bit depth                      : 8 bits
Scan type                      : Progressive
Bits/(Pixel*Frame)             : 0.160
Stream size                    : 71.3 MiB (97%)
Language                       : English
Color range                    : Limited
Color primaries                : BT.709
Transfer characteristics       : BT.709
Matrix coefficients            : BT.709
Codec configuration box        : avcC

Audio
ID                             : 2
Format                         : ADPCM
Codec ID                       : 11
Codec ID/Hint                  : Intel
Duration                       : 1 min 0 s
Bit rate mode                  : Constant
Bit rate                       : 272 kb/s
Channel(s)                     : 2 channels
Channel layout                 : L R
Sampling rate                  : 32.0 kHz
Stream size                    : 1.95 MiB (3%)
Language                       : English

**Comment by xufuji456** [comment]
你是想剪切视频同时，修改音频编码器是吧。
你这个mov视频中的音频流是ADPCM，目前没有把这个解码器编译进ffmpeg.so库。
一般音频mp3、aac、wma、flac等是支持转码的，这样指定编码器: -acodec libmp3lame，不要-an。
如果你确实有ADPCM音频转码的需求，你可以重新编译ffmpeg，或者我给你编译。

**Comment by zijin2014** [comment]
> 你是想剪切视频同时，修改音频编码器是吧。
> 你这个mov视频中的音频流是ADPCM，目前没有把这个解码器编译进ffmpeg.so库。
> 一般音频mp3、aac、wma、flac等是支持转码的，这样指定编码器: -acodec libmp3lame，不要-an。
> 如果你确实有ADPCM音频转码的需求，你可以重新编译ffmpeg，或者我给你编译。

是的呢，想裁剪mov，并且修改音频编码，然后转码为mp4（因为分享到微信，微信播放没有声音）；这个问题卡了我好久，大神帮我编译一下嘛，感谢大神

**Comment by xufuji456** [comment]
没问题，你是只要mov剪切功能吗？
对编译出来的so库大小有没严格要求

**Comment by zijin2014** [comment]
是的，大小没太大要求，还有ts的剪切，转码，现在的可以支持ts

**Comment by xufuji456** [comment]
你邮箱多少，我把编译好的so库发给你

**Comment by zijin2014** [comment]
> 你邮箱多少，我把编译好的so库发给你

1254418162@qq.com  感谢🙏

**Comment by xufuji456** [comment]
发给你了，你替换armeabi-v7a和arm64-v8a平台的ffmpeg.so库试下

**Comment by xufuji456** [comment]
如果mov还无法剪切，把视频发给我

**Comment by zijin2014** [comment]
> 如果mov还无法剪切，把视频发给我

大神视频文件已经通过邮箱发送给你了

**Comment by xufuji456** [comment]
给你重新发了ffmpeg库，我试了可以指定音频编码器进行视频剪切了。
命令：-acodec libmp3lame

**Comment by xufuji456** [comment]
你的文件名后缀是MOV大写，我原来判断文件后缀用小写，文件后缀判断那里需要稍微改下

**Comment by wjj201411** [comment]
> 给大神点赞，相当可以！mov视频裁剪完，分享到微信好友视频缩略图是黑的，QQ抖音等社交平台没有问题，这是啥原因

**Comment by zijin2014** [comment]
> 完美的支持了mov,还有ts，移植到项目到时候可以作为一个module注意不要改变了包名，希望后来者少踩坑，再次感谢！大神可以把赞助码发出来呗

**Comment by tianminggh** [comment]
> 你邮箱多少，我把编译好的so库发给你

大佬  编译脚本能发一下吗？我也遇到这个问题
