### ISSUE TITLE
播放RTSP出错： No such file or directory

### ISSUE THREAD

**Issue by Mokyyds** [xufuji456/FFmpegAndroid#93]
请问作者播放RTSP黑屏并弹出“Unknown”窗口，LOG错误信息是： No such file or directory。要怎么解决呢？流地址是没问题的，不知道是那个路径没有？

**Comment by xufuji456** [comment]
@Peachou  我更换了可用直播地址，你更新代码试下OnLive模块

**Comment by Mokyyds** [comment]
> @Peachou 我更换了可用直播地址，你更新代码试下OnLive模块
非常感谢，我换成海康威视摄像头的RTSP地址可以播放了，还想请问一下如何加入截图和录像功能呢？

**Comment by xufuji456** [comment]
截图：可以调用TextView的getBitmap方法截取当前帧，或者调用FFmpeg截取任意帧。
录像：你是要录制当前播放屏幕，还是保存当前视频的一段呢

**Comment by Mokyyds** [comment]
> 截图：可以调用TextView的getBitmap方法截取当前帧，或者调用FFmpeg截取任意帧。
> 录像：你是要录制当前播放屏幕，还是保存当前视频的一段呢

录像我想只录rtsp播放的内容，不是录屏。如何能录制rtsp流呢？手动点击录制停止。

**Comment by xufuji456** [comment]
rtsp直播步骤:拉流->解码->播放
比较好的方法，在ijkplayer解码前把音视频流保存起来

**Comment by Mokyyds** [comment]
> rtsp直播步骤:拉流->解码->播放
> 比较好的方法，在ijkplayer解码前把音视频流保存起来

您能不能把您优化的ikplayer源码也开源一下呢？我想加到这一层上

**Comment by xufuji456** [comment]
修改的源码我没有保存，不过我在博客上有介绍完整的修改步骤
https://blog.csdn.net/u011686167/article/details/85256101

**Comment by Dreamskya** [comment]
@xufuji456 博主，更新了项目，测试了你更新的rtmp地址，播放的时候，有点卡卡的效果。是解码不过来导致的吗？肉眼可以看的出来，但不会很严重。不流畅。

**Comment by Dreamskya** [comment]
@xufuji456 onlive 工程
