### ISSUE TITLE
调用不到jni方法

### ISSUE THREAD

**Issue by pkxutao** [xufuji456/FFmpegAndroid#96]
大神你好，我是第一次搞jni方法，我把so文件复制过来后，FFmpegCmd也放在了com.frank.ffmpeg包下，但是调用的时候提示找不到handle方法，搜索了好多地方也没解决，只能来问你了，谢谢
`2020-01-02 15:24:38.821 2701-3589/? E/com.funz: No implementation found for int com.frank.ffmpeg.FFmpegCmd.handle(java.lang.String[]) (tried Java_com_frank_ffmpeg_FFmpegCmd_handle and Java_com_frank_ffmpeg_FFmpegCmd_handle___3Ljava_lang_String_2)`

**Comment by xufuji456** [comment]
你把工程结构截图出来看下

**Comment by pkxutao** [comment]
解决了，我自己搞错了，避免后面的人犯同样的错误，看看下面
首先
`System.loadLibrary("media-handle");`
这个media-handle包没错，不用改名，下面指定jni文件夹路径必须修改一下，不能和demo一样
`jniLibs.srcDirs = ['libs']`
改为
`jniLibs.srcDirs = ['libs','./src/main/jniLibs']`
我一直找错方向了，谢谢作者

**Comment by xufuji456** [comment]
不用客气，解决了就好

**Comment by hdProj** [comment]
添加so进来之后，提示是这样的，有点懵
java.lang.UnsatisfiedLinkError: dlopen failed: library "libmedia-handle.so" not found
