### ISSUE TITLE
android studio build apk时报错

### ISSUE THREAD

**Issue by Netech-DevNote** [xufuji456/FFmpegAndroid#97]
大佬们，我在android studio上build生成apk时报错如下，请问你们有遇到过吗？

Build command failed.
Error while executing process D:\android\Sdk\cmake\3.10.2.4988404\bin\cmake.exe with arguments {--build E:\android\googleplay\FFmpegAndroid\app\.externalNativeBuild\cmake\debug\armeabi-v7a --target media-handle}
[1/1] Linking CXX shared library ..\..\..\..\build\intermediates\cmake\debug\obj\armeabi-v7a\libmedia-handle.so
FAILED: ../../../../build/intermediates/cmake/debug/obj/armeabi-v7a/libmedia-handle.so 
cmd.exe /C "cd . && D:\android\Sdk\ndk-bundle\toolchains\llvm\prebuilt\windows-x86_64\bin\clang++.exe --target=armv7-none-linux-androideabi21 --gcc-toolchain=D:/android/Sdk/ndk-bundle/toolchains/llvm/prebuilt/windows-x86_64 --sysroot=D:/android/Sdk/ndk-bundle/toolchains/llvm/prebuilt/windows-x86_64/sysroot -fPIC -g -DANDROID -fdata-sections -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -fno-addrsig -march=armv7-a -mthumb -Wa,--noexecstack -Wformat -Werror=format-security   -std=gnu++11 -O0 -fno-limit-debug-info  -Wl,--exclude-libs,libgcc.a -Wl,--exclude-libs,libatomic.a -static-libstdc++ -Wl,--build-id -Wl,--warn-shared-textrel -Wl,--fatal-warnings -Wl,--exclude-libs,libunwind.a -Wl,--no-undefined -Qunused-arguments -Wl,-z,noexecstack -shared -Wl,-soname,libmedia-handle.so -o ..\..\..\..\build\intermediates\cmake\debug\obj\armeabi-v7a\libmedia-handle.so CMakeFiles/media-handle.dir/src/main/cpp/ffmpeg/cmdutils.c.o CMakeFiles/media-handle.dir/src/main/cpp/ffmpeg/ffmpeg.c.o CMakeFiles/media-handle.dir/src/main/cpp/ffmpeg/ffmpeg_filter.c.o CMakeFiles/media-handle.dir/src/main/cpp/ffmpeg/ffmpeg_opt.c.o CMakeFiles/media-handle.dir/src/main/cpp/ffmpeg_cmd.c.o CMakeFiles/media-handle.dir/src/main/cpp/audio_player.c.o CMakeFiles/media-handle.dir/src/main/cpp/openSL_audio_player.c.o CMakeFiles/media-handle.dir/src/main/cpp/video_player.c.o CMakeFiles/media-handle.dir/src/main/cpp/ffmpeg_pusher.cpp.o CMakeFiles/media-handle.dir/src/main/cpp/AVpacket_queue.c.o CMakeFiles/media-handle.dir/src/main/cpp/media_player.c.o CMakeFiles/media-handle.dir/src/main/cpp/video_filter.c.o CMakeFiles/media-handle.dir/src/main/cpp/audio_lame.c.o CMakeFiles/media-handle.dir/src/main/cpp/fast_start.c.o  ../../../../libs/armeabi-v7a/libffmpeg.so -landroid -ljnigraphics -lOpenSLES -llog -latomic -lm && cd ."
../../../../src/main/cpp/audio_lame.c:9: error: undefined reference to 'lame_init'
../../../../src/main/cpp/audio_lame.c:10: error: undefined reference to 'lame_init_params'
../../../../src/main/cpp/audio_lame.c:22: error: undefined reference to 'lame_init'
../../../../src/main/cpp/audio_lame.c:23: error: undefined reference to 'lame_set_in_samplerate'
../../../../src/main/cpp/audio_lame.c:24: error: undefined reference to 'lame_set_num_channels'
../../../../src/main/cpp/audio_lame.c:25: error: undefined reference to 'lame_set_out_samplerate'
../../../../src/main/cpp/audio_lame.c:26: error: undefined reference to 'lame_set_brate'
../../../../src/main/cpp/audio_lame.c:27: error: undefined reference to 'lame_set_quality'
../../../../src/main/cpp/audio_lame.c:28: error: undefined reference to 'lame_set_scale'
../../../../src/main/cpp/audio_lame.c:29: error: undefined reference to 'lame_set_VBR_q'
../../../../src/main/cpp/audio_lame.c:30: error: undefined reference to 'lame_set_VBR_mean_bitrate_kbps'
../../../../src/main/cpp/audio_lame.c:31: error: undefined reference to 'lame_set_lowpassfreq'
../../../../src/main/cpp/audio_lame.c:32: error: undefined reference to 'lame_set_highpassfreq'
../../../../src/main/cpp/audio_lame.c:36: error: undefined reference to 'lame_set_mode'
../../../../src/main/cpp/audio_lame.c:39: error: undefined reference to 'lame_set_mode'
../../../../src/main/cpp/audio_lame.c:42: error: undefined reference to 'lame_set_mode'
../../../../src/main/cpp/audio_lame.c:45: error: undefined reference to 'lame_set_mode'
../../../../src/main/cpp/audio_lame.c:54: error: undefined reference to 'lame_set_VBR'
../../../../src/main/cpp/audio_lame.c:57: error: undefined reference to 'lame_set_VBR'
../../../../src/main/cpp/audio_lame.c:60: error: undefined reference to 'lame_set_VBR'
../../../../src/main/cpp/audio_lame.c:63: error: undefined reference to 'lame_set_VBR'
../../../../src/main/cpp/audio_lame.c:97: error: undefined reference to 'id3tag_init'
../../../../src/main/cpp/audio_lame.c:100: error: undefined reference to 'id3tag_set_title'
../../../../src/main/cpp/audio_lame.c:104: error: undefined reference to 'id3tag_set_artist'
../../../../src/main/cpp/audio_lame.c:108: error: undefined reference to 'id3tag_set_album'
../../../../src/main/cpp/audio_lame.c:112: error: undefined reference to 'id3tag_set_year'
../../../../src/main/cpp/audio_lame.c:116: error: undefined reference to 'id3tag_set_comment'
../../../../src/main/cpp/audio_lame.c:121: error: undefined reference to 'lame_init_params'
../../../../src/main/cpp/audio_lame.c:138: error: undefined reference to 'lame_encode_buffer'
../../../../src/main/cpp/audio_lame.c:156: error: undefined reference to 'lame_encode_buffer_interleaved'
../../../../src/main/cpp/audio_lame.c:171: error: undefined reference to 'lame_encode_flush'
../../../../src/main/cpp/audio_lame.c:179: error: undefined reference to 'lame_close'
clang++: error: linker command failed with exit code 1 (use -v to see invocation)
ninja: build stopped: subcommand failed.

**Comment by iopa788** [comment]
@ar-world  你build 成功了么 告诉我下

**Comment by Netech-DevNote** [comment]
@iopa788 你也遇到这个问题了吗？  我没有啊，整了好久
@xufuji456 大佬，能帮忙看看么？

**Comment by xufuji456** [comment]
@ar-world @iopa788   把cmakeList.txt的关于MP3的两处注释去掉试下

**Comment by xufuji456** [comment]
你们更新代码试下

**Comment by Netech-DevNote** [comment]
@xufuji456 可以编译通过了，感谢。

**Comment by xufuji456** [comment]
@ar-world 不用客气，看你的昵称是搞AR的

**Comment by Netech-DevNote** [comment]
哈哈，是的，想做AR短视频

**Comment by q1170541047** [comment]
> @ar-world @iopa788 把cmakeList.txt的关于MP3的两处注释去掉试下

这个文件最新版没有关于Mp3了吧，我也是一模一样的错误
