### ISSUE TITLE
作者您好，下载您的DEMO 目前再音视频处理这款，所有模块都闪退，请问是哪里原因呢

### ISSUE THREAD

**Issue by 1173859245** [xufuji456/FFmpegAndroid#98]
视频处理模块所有功能闪退，权限已给，求告知

**Comment by xufuji456** [comment]
你的什么手机什么API版本，有没报错日志

**Comment by AnotherSkyBoy** [comment]
Fatal signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x2c in tid 5614 (Thread-5), pid 5447 (om.frank.ffmpeg)

**Comment by AnotherSkyBoy** [comment]
D/mali_winsys: EGLint new_window_surface(egl_winsys_display *, void *, EGLSurface, EGLConfig, egl_winsys_surface **, EGLBoolean) returns 0x3000
Process 5447 terminated.

**Comment by zhaichuankai** [comment]
我也遇到了  老哥- -

**Comment by TsaiYongChuan** [comment]
我也是 华为 mate 20 pro Android10.0版本

**Comment by lzc820** [comment]
应该是不支持安卓系统10的版本。

**Comment by xufuji456** [comment]
我的华为Android10试了试可以的

**Comment by pie-tk** [comment]
@xufuji456 我也是，好像用到ffmpeg的模块都没用，demo下载下来后，c文件和头文件中include都是报红

**Comment by xufuji456** [comment]
更新代码试下
